// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../index.js";

/**
 * @example
 *     {
 *         body: {
 *             agent: "agent"
 *         }
 *     }
 */
export interface CreateSessionRequest {
    idempotencyKey?: string | null;
    body: HaiAgents.SessionRequest;
}
