// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         bucket: "bucket",
 *         key: "key"
 *     }
 */
export interface GetSessionResourceRequest {
    id: string;
    bucket: string;
    key: string;
}
