// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface GetSessionChangesRequest {
    id: string;
    fromIndex?: number;
    limit?: number | null;
    includeEvents?: boolean;
    waitForSeconds?: number;
}
