// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface GetSessionChangesRequest {
    id: string;
    from_index?: number;
    limit?: number | null;
    include_events?: boolean;
    wait_for_seconds?: number;
}
