// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListSessionsRequest {
    owner?: HaiAgents.ListSessionsRequestOwner;
    status?: HaiAgents.TrajectoryStatus[] | null;
    agent?: string[] | null;
    groupId?: string | null;
    parentSessionId?: string | null;
    /** Only sessions created by this schedule. */
    scheduleId?: string | null;
    /** Case-insensitive match on the session's first message or answer. */
    search?: string | null;
    createdBefore?: Date | null;
    createdAfter?: Date | null;
    finishedBefore?: Date | null;
    finishedAfter?: Date | null;
    /** Page number (1-based) */
    page?: number;
    /** Number of items per page */
    size?: number;
    /** Sort by field */
    sort?: HaiAgents.ListSessionsRequestSortItem[] | null;
}
