// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListSessionsRequest {
    owner?: HaiAgents.ListSessionsRequestOwner;
    status?: HaiAgents.TrajectoryStatus[] | null;
    agent?: string[] | null;
    group_id?: string | null;
    parent_session_id?: string | null;
    /** Case-insensitive match on the session's first message or answer. */
    search?: string | null;
    created_before?: string | null;
    created_after?: string | null;
    finished_before?: string | null;
    finished_after?: string | null;
    /** Page number (1-based) */
    page?: number;
    /** Number of items per page */
    size?: number;
    /** Sort by field */
    sort?: HaiAgents.ListSessionsRequestSortItem[] | null;
}
