// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface ListSessionEventsRequest {
    id: string;
    page?: number;
    size?: number;
    sort?: HaiAgents.ListSessionEventsRequestSortItem[] | null;
    type?: string | null;
}
