// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         body: {
 *             type: "user_message",
 *             message: "message",
 *             type: "user_message"
 *         }
 *     }
 */
export interface SendSessionMessagesRequest {
    id: string;
    body: HaiAgents.SendSessionMessagesRequestBody;
}
