// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         eventIndex: 1,
 *         body: {
 *             success: true
 *         }
 *     }
 */
export interface SubmitEventFeedbackRequest {
    id: string;
    eventIndex: number;
    body: HaiAgents.Feedback;
}
