// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const ListSessionsRequestSortItem: core.serialization.Schema<
    serializers.ListSessionsRequestSortItem.Raw,
    HaiAgents.ListSessionsRequestSortItem
> = core.serialization.enum_(["created_at", "-created_at"]);

export declare namespace ListSessionsRequestSortItem {
    export type Raw = "created_at" | "-created_at";
}
