// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const ListSessionsRequestOwner: core.serialization.Schema<
    serializers.ListSessionsRequestOwner.Raw,
    HaiAgents.ListSessionsRequestOwner
> = core.serialization.enum_(["me", "me-in-organization", "organization", "me-or-organization"]);

export declare namespace ListSessionsRequestOwner {
    export type Raw = "me" | "me-in-organization" | "organization" | "me-or-organization";
}
