// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const ListSessionEventsRequestSortItem: core.serialization.Schema<
    serializers.ListSessionEventsRequestSortItem.Raw,
    HaiAgents.ListSessionEventsRequestSortItem
> = core.serialization.enum_(["timestamp", "-timestamp"]);

export declare namespace ListSessionEventsRequestSortItem {
    export type Raw = "timestamp" | "-timestamp";
}
