// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { ErrorEvent } from "../../../types/ErrorEvent.js";
import { ToolResultBatch } from "../../../types/ToolResultBatch.js";
import { ToolResultEvent } from "../../../types/ToolResultEvent.js";

export const SendSessionToolResultsRequestBody: core.serialization.Schema<
    serializers.SendSessionToolResultsRequestBody.Raw,
    HaiAgents.SendSessionToolResultsRequestBody
> = core.serialization.undiscriminatedUnion([ToolResultEvent, ErrorEvent, ToolResultBatch]);

export declare namespace SendSessionToolResultsRequestBody {
    export type Raw = ToolResultEvent.Raw | ErrorEvent.Raw | ToolResultBatch.Raw;
}
