// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { UserMessageBatch } from "../../../types/UserMessageBatch.js";
import { UserMessageEvent } from "../../../types/UserMessageEvent.js";

export const SendSessionMessagesRequestBody: core.serialization.Schema<
    serializers.SendSessionMessagesRequestBody.Raw,
    HaiAgents.SendSessionMessagesRequestBody
> = core.serialization
    .union("type", {
        user_message: UserMessageEvent,
        batch: UserMessageBatch,
    })
    .transform<HaiAgents.SendSessionMessagesRequestBody>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace SendSessionMessagesRequestBody {
    export type Raw = SendSessionMessagesRequestBody.UserMessage | SendSessionMessagesRequestBody.Batch;

    export interface UserMessage extends UserMessageEvent.Raw {
        type: "user_message";
    }

    export interface Batch extends UserMessageBatch.Raw {
        type: "batch";
    }
}
