// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         profileId: "profile_id",
 *         name: "name",
 *         browserName: "browser_name",
 *         browserVersion: "browser_version"
 *     }
 */
export interface BrowserProfileCreate {
    profileId: string;
    name: string;
    browserName: string;
    browserVersion: string;
    description?: string | null;
    labels?: Record<string, string>;
}
