// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         profileId: "profile_id"
 *     }
 */
export interface DeleteBrowserProfileRequest {
    profileId: string;
}
