// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         browserName: "browser_name"
 *     }
 */
export interface GetDefaultBrowserProfileRequest {
    /** Browser flavor, e.g. 'chromium' */
    browserName: string;
}
