// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../api/index.js";
import type * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { SessionChanges } from "../../../types/SessionChanges.js";

export const Response: core.serialization.Schema<
    serializers.sessions.getSessionChanges.Response.Raw,
    HaiAgents.SessionChanges | undefined
> = SessionChanges.optional();

export declare namespace Response {
    export type Raw = SessionChanges.Raw | null | undefined;
}
