// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sessionId: "session_id",
 *         path: "path",
 *         contentBase64: "content_base64"
 *     }
 */
export interface WriteFileRequest {
    sessionId: string;
    path: string;
    contentBase64: string;
}
