// This file was auto-generated by Fern from our API Definition.

export const HaiAgentsEnvironment = {
    Default: "https://agp.eu.hcompany.ai",
} as const;

export type HaiAgentsEnvironment = typeof HaiAgentsEnvironment.Default;
