// This file was auto-generated by Fern from our API Definition.

export const HaiAgentsEnvironment = {
    Eu: "https://agp.eu.hcompany.ai",
    Us: "https://agp.hcompany.ai",
} as const;

export type HaiAgentsEnvironment = typeof HaiAgentsEnvironment.Eu | typeof HaiAgentsEnvironment.Us;
