// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CancelSessionApiV2SessionsIdDeleteData,
  CancelSessionApiV2SessionsIdDeleteErrors,
  CancelSessionApiV2SessionsIdDeleteResponses,
  CreateAgentApiV2AgentsPostData,
  CreateAgentApiV2AgentsPostErrors,
  CreateAgentApiV2AgentsPostResponses,
  CreateEnvironmentApiV2EnvironmentsPostData,
  CreateEnvironmentApiV2EnvironmentsPostErrors,
  CreateEnvironmentApiV2EnvironmentsPostResponses,
  CreateMemoryApiV2MemoriesPostData,
  CreateMemoryApiV2MemoriesPostErrors,
  CreateMemoryApiV2MemoriesPostResponses,
  CreateSessionApiV2SessionsPostData,
  CreateSessionApiV2SessionsPostErrors,
  CreateSessionApiV2SessionsPostResponses,
  CreateSkillApiV2SkillsPostData,
  CreateSkillApiV2SkillsPostErrors,
  CreateSkillApiV2SkillsPostResponses,
  DeleteAgentApiV2AgentsAgentIdentifierDeleteData,
  DeleteAgentApiV2AgentsAgentIdentifierDeleteErrors,
  DeleteAgentApiV2AgentsAgentIdentifierDeleteResponses,
  DeleteEnvironmentApiV2EnvironmentsEnvIdentifierDeleteData,
  DeleteEnvironmentApiV2EnvironmentsEnvIdentifierDeleteErrors,
  DeleteEnvironmentApiV2EnvironmentsEnvIdentifierDeleteResponses,
  DeleteMemoryApiV2MemoriesIdDeleteData,
  DeleteMemoryApiV2MemoriesIdDeleteErrors,
  DeleteMemoryApiV2MemoriesIdDeleteResponses,
  DeleteSkillApiV2SkillsIdDeleteData,
  DeleteSkillApiV2SkillsIdDeleteErrors,
  DeleteSkillApiV2SkillsIdDeleteResponses,
  ForceSessionAnswerApiV2SessionsIdForceAnswerPostData,
  ForceSessionAnswerApiV2SessionsIdForceAnswerPostErrors,
  ForceSessionAnswerApiV2SessionsIdForceAnswerPostResponses,
  GetAgentApiV2AgentsAgentIdentifierGetData,
  GetAgentApiV2AgentsAgentIdentifierGetErrors,
  GetAgentApiV2AgentsAgentIdentifierGetResponses,
  GetEnvironmentApiV2EnvironmentsEnvIdentifierGetData,
  GetEnvironmentApiV2EnvironmentsEnvIdentifierGetErrors,
  GetEnvironmentApiV2EnvironmentsEnvIdentifierGetResponses,
  GetMemoryApiV2MemoriesIdGetData,
  GetMemoryApiV2MemoriesIdGetErrors,
  GetMemoryApiV2MemoriesIdGetResponses,
  GetSessionApiV2SessionsIdGetData,
  GetSessionApiV2SessionsIdGetErrors,
  GetSessionApiV2SessionsIdGetResponses,
  GetSessionChangesApiV2SessionsIdChangesGetData,
  GetSessionChangesApiV2SessionsIdChangesGetErrors,
  GetSessionChangesApiV2SessionsIdChangesGetResponses,
  GetSessionQuotaApiV2SessionsQuotaGetData,
  GetSessionQuotaApiV2SessionsQuotaGetErrors,
  GetSessionQuotaApiV2SessionsQuotaGetResponses,
  GetSessionResourceApiV2SessionsIdResourcesBucketKeyGetData,
  GetSessionResourceApiV2SessionsIdResourcesBucketKeyGetErrors,
  GetSessionResourceApiV2SessionsIdResourcesBucketKeyGetResponses,
  GetSessionStatusApiV2SessionsIdStatusGetData,
  GetSessionStatusApiV2SessionsIdStatusGetErrors,
  GetSessionStatusApiV2SessionsIdStatusGetResponses,
  GetSkillApiV2SkillsIdGetData,
  GetSkillApiV2SkillsIdGetErrors,
  GetSkillApiV2SkillsIdGetResponses,
  ListAgentsApiV2AgentsGetData,
  ListAgentsApiV2AgentsGetErrors,
  ListAgentsApiV2AgentsGetResponses,
  ListEnvironmentsApiV2EnvironmentsGetData,
  ListEnvironmentsApiV2EnvironmentsGetErrors,
  ListEnvironmentsApiV2EnvironmentsGetResponses,
  ListMemoriesApiV2MemoriesGetData,
  ListMemoriesApiV2MemoriesGetErrors,
  ListMemoriesApiV2MemoriesGetResponses,
  ListSessionEventsApiV2SessionsIdEventsGetData,
  ListSessionEventsApiV2SessionsIdEventsGetErrors,
  ListSessionEventsApiV2SessionsIdEventsGetResponses,
  ListSessionsApiV2SessionsGetData,
  ListSessionsApiV2SessionsGetErrors,
  ListSessionsApiV2SessionsGetResponses,
  ListSkillsApiV2SkillsGetData,
  ListSkillsApiV2SkillsGetErrors,
  ListSkillsApiV2SkillsGetResponses,
  PauseSessionApiV2SessionsIdPausePostData,
  PauseSessionApiV2SessionsIdPausePostErrors,
  PauseSessionApiV2SessionsIdPausePostResponses,
  ResumeSessionApiV2SessionsIdResumePostData,
  ResumeSessionApiV2SessionsIdResumePostErrors,
  ResumeSessionApiV2SessionsIdResumePostResponses,
  SendSessionMessagesApiV2SessionsIdMessagesPostData,
  SendSessionMessagesApiV2SessionsIdMessagesPostErrors,
  SendSessionMessagesApiV2SessionsIdMessagesPostResponses,
  ShareSessionApiV2SessionsIdSharePostData,
  ShareSessionApiV2SessionsIdSharePostErrors,
  ShareSessionApiV2SessionsIdSharePostResponses,
  SubmitEventFeedbackApiV2SessionsIdEventsEventIndexFeedbackPutData,
  SubmitEventFeedbackApiV2SessionsIdEventsEventIndexFeedbackPutErrors,
  SubmitEventFeedbackApiV2SessionsIdEventsEventIndexFeedbackPutResponses,
  SubmitSessionFeedbackApiV2SessionsIdFeedbackPostData,
  SubmitSessionFeedbackApiV2SessionsIdFeedbackPostErrors,
  SubmitSessionFeedbackApiV2SessionsIdFeedbackPostResponses,
  UnshareSessionApiV2SessionsIdShareDeleteData,
  UnshareSessionApiV2SessionsIdShareDeleteErrors,
  UnshareSessionApiV2SessionsIdShareDeleteResponses,
  UpdateAgentApiV2AgentsAgentIdentifierPutData,
  UpdateAgentApiV2AgentsAgentIdentifierPutErrors,
  UpdateAgentApiV2AgentsAgentIdentifierPutResponses,
  UpdateEnvironmentApiV2EnvironmentsEnvIdentifierPutData,
  UpdateEnvironmentApiV2EnvironmentsEnvIdentifierPutErrors,
  UpdateEnvironmentApiV2EnvironmentsEnvIdentifierPutResponses,
  UpdateMemoryApiV2MemoriesIdPutData,
  UpdateMemoryApiV2MemoriesIdPutErrors,
  UpdateMemoryApiV2MemoriesIdPutResponses,
  UpdateSkillApiV2SkillsIdPutData,
  UpdateSkillApiV2SkillsIdPutErrors,
  UpdateSkillApiV2SkillsIdPutResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * List Sessions
 *
 * List sessions visible to ``user``.
 */
export const listSessionsApiV2SessionsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListSessionsApiV2SessionsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListSessionsApiV2SessionsGetResponses,
    ListSessionsApiV2SessionsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions",
    ...options,
  });

/**
 * Create Session
 *
 * Create an agentic session.
 *
 * Pass ``Idempotency-Key`` for safe retries: identical requests within 24h
 * return the original session; reuse with a different body returns 422.
 */
export const createSessionApiV2SessionsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateSessionApiV2SessionsPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateSessionApiV2SessionsPostResponses,
    CreateSessionApiV2SessionsPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Session Quota
 *
 * Concurrent-session quota for the authenticated user.
 */
export const getSessionQuotaApiV2SessionsQuotaGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetSessionQuotaApiV2SessionsQuotaGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetSessionQuotaApiV2SessionsQuotaGetResponses,
    GetSessionQuotaApiV2SessionsQuotaGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/quota",
    ...options,
  });

/**
 * Cancel Session
 *
 * Cancel the session.
 */
export const cancelSessionApiV2SessionsIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CancelSessionApiV2SessionsIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    CancelSessionApiV2SessionsIdDeleteResponses,
    CancelSessionApiV2SessionsIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}",
    ...options,
  });

/**
 * Get Session
 *
 * Get a session.
 */
export const getSessionApiV2SessionsIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetSessionApiV2SessionsIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSessionApiV2SessionsIdGetResponses,
    GetSessionApiV2SessionsIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}",
    ...options,
  });

/**
 * Get Session Status
 *
 * Get a session's live status.
 */
export const getSessionStatusApiV2SessionsIdStatusGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetSessionStatusApiV2SessionsIdStatusGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSessionStatusApiV2SessionsIdStatusGetResponses,
    GetSessionStatusApiV2SessionsIdStatusGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}/status",
    ...options,
  });

/**
 * Send Session Messages
 *
 * Send a user message (single or batch).
 */
export const sendSessionMessagesApiV2SessionsIdMessagesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    SendSessionMessagesApiV2SessionsIdMessagesPostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    SendSessionMessagesApiV2SessionsIdMessagesPostResponses,
    SendSessionMessagesApiV2SessionsIdMessagesPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}/messages",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Pause Session
 *
 * Pause the session.
 */
export const pauseSessionApiV2SessionsIdPausePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PauseSessionApiV2SessionsIdPausePostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PauseSessionApiV2SessionsIdPausePostResponses,
    PauseSessionApiV2SessionsIdPausePostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}/pause",
    ...options,
  });

/**
 * Resume Session
 *
 * Resume the session.
 */
export const resumeSessionApiV2SessionsIdResumePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ResumeSessionApiV2SessionsIdResumePostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ResumeSessionApiV2SessionsIdResumePostResponses,
    ResumeSessionApiV2SessionsIdResumePostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}/resume",
    ...options,
  });

/**
 * Force Session Answer
 *
 * Ask the agent to emit a final answer on its next step.
 */
export const forceSessionAnswerApiV2SessionsIdForceAnswerPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ForceSessionAnswerApiV2SessionsIdForceAnswerPostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    ForceSessionAnswerApiV2SessionsIdForceAnswerPostResponses,
    ForceSessionAnswerApiV2SessionsIdForceAnswerPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}/force_answer",
    ...options,
  });

/**
 * Get Session Changes
 *
 * Long-poll for new events since ``from_index``; 204 if none arrive within ``wait_for_seconds``.
 */
export const getSessionChangesApiV2SessionsIdChangesGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetSessionChangesApiV2SessionsIdChangesGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetSessionChangesApiV2SessionsIdChangesGetResponses,
    GetSessionChangesApiV2SessionsIdChangesGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}/changes",
    ...options,
  });

/**
 * List Session Events
 *
 * Paginated event history. Use ``/changes`` for live tailing.
 */
export const listSessionEventsApiV2SessionsIdEventsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListSessionEventsApiV2SessionsIdEventsGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ListSessionEventsApiV2SessionsIdEventsGetResponses,
    ListSessionEventsApiV2SessionsIdEventsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}/events",
    ...options,
  });

/**
 * Submit Session Feedback
 *
 * Record semantic-success feedback on the whole session.
 */
export const submitSessionFeedbackApiV2SessionsIdFeedbackPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    SubmitSessionFeedbackApiV2SessionsIdFeedbackPostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    SubmitSessionFeedbackApiV2SessionsIdFeedbackPostResponses,
    SubmitSessionFeedbackApiV2SessionsIdFeedbackPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}/feedback",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Submit Event Feedback
 *
 * Record feedback on a single event in the session's history.
 */
export const submitEventFeedbackApiV2SessionsIdEventsEventIndexFeedbackPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    SubmitEventFeedbackApiV2SessionsIdEventsEventIndexFeedbackPutData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).put<
    SubmitEventFeedbackApiV2SessionsIdEventsEventIndexFeedbackPutResponses,
    SubmitEventFeedbackApiV2SessionsIdEventsEventIndexFeedbackPutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}/events/{event_index}/feedback",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Unshare Session
 *
 * Revoke public access to the session.
 */
export const unshareSessionApiV2SessionsIdShareDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UnshareSessionApiV2SessionsIdShareDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    UnshareSessionApiV2SessionsIdShareDeleteResponses,
    UnshareSessionApiV2SessionsIdShareDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}/share",
    ...options,
  });

/**
 * Share Session
 *
 * Make the session publicly readable; returns the share URL path.
 */
export const shareSessionApiV2SessionsIdSharePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ShareSessionApiV2SessionsIdSharePostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ShareSessionApiV2SessionsIdSharePostResponses,
    ShareSessionApiV2SessionsIdSharePostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}/share",
    ...options,
  });

/**
 * Get Session Resource
 *
 * Redirect to a presigned S3 URL for a session-owned resource.
 */
export const getSessionResourceApiV2SessionsIdResourcesBucketKeyGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetSessionResourceApiV2SessionsIdResourcesBucketKeyGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetSessionResourceApiV2SessionsIdResourcesBucketKeyGetResponses,
    GetSessionResourceApiV2SessionsIdResourcesBucketKeyGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}/resources/{bucket}/{key}",
    ...options,
  });

/**
 * List Memories
 *
 * List org memories; optional exact-namespace and key-prefix filters.
 */
export const listMemoriesApiV2MemoriesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListMemoriesApiV2MemoriesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListMemoriesApiV2MemoriesGetResponses,
    ListMemoriesApiV2MemoriesGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/memories",
    ...options,
  });

/**
 * Create Memory
 *
 * Upsert a memory by ``(org_id, namespace, key)``. 201 on create, 200 on update.
 */
export const createMemoryApiV2MemoriesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateMemoryApiV2MemoriesPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateMemoryApiV2MemoriesPostResponses,
    CreateMemoryApiV2MemoriesPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/memories",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Memory
 *
 * Delete a memory.
 */
export const deleteMemoryApiV2MemoriesIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteMemoryApiV2MemoriesIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteMemoryApiV2MemoriesIdDeleteResponses,
    DeleteMemoryApiV2MemoriesIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/memories/{id}",
    ...options,
  });

/**
 * Get Memory
 *
 * Get a memory by id.
 */
export const getMemoryApiV2MemoriesIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetMemoryApiV2MemoriesIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetMemoryApiV2MemoriesIdGetResponses,
    GetMemoryApiV2MemoriesIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/memories/{id}",
    ...options,
  });

/**
 * Update Memory
 *
 * Update a memory's value.
 */
export const updateMemoryApiV2MemoriesIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateMemoryApiV2MemoriesIdPutData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpdateMemoryApiV2MemoriesIdPutResponses,
    UpdateMemoryApiV2MemoriesIdPutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/memories/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Skills
 *
 * List skills for the current org, optionally filtered by name prefix.
 */
export const listSkillsApiV2SkillsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListSkillsApiV2SkillsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListSkillsApiV2SkillsGetResponses,
    ListSkillsApiV2SkillsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/skills",
    ...options,
  });

/**
 * Create Skill
 *
 * Create a skill.
 */
export const createSkillApiV2SkillsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateSkillApiV2SkillsPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateSkillApiV2SkillsPostResponses,
    CreateSkillApiV2SkillsPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/skills",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Skill
 *
 * Delete a skill.
 */
export const deleteSkillApiV2SkillsIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteSkillApiV2SkillsIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteSkillApiV2SkillsIdDeleteResponses,
    DeleteSkillApiV2SkillsIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/skills/{id}",
    ...options,
  });

/**
 * Get Skill
 *
 * Get a skill by id.
 */
export const getSkillApiV2SkillsIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetSkillApiV2SkillsIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSkillApiV2SkillsIdGetResponses,
    GetSkillApiV2SkillsIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/skills/{id}",
    ...options,
  });

/**
 * Update Skill
 *
 * Update a skill's content.
 */
export const updateSkillApiV2SkillsIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateSkillApiV2SkillsIdPutData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpdateSkillApiV2SkillsIdPutResponses,
    UpdateSkillApiV2SkillsIdPutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/skills/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Environments
 *
 * List reserved + caller's org environments.
 */
export const listEnvironmentsApiV2EnvironmentsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListEnvironmentsApiV2EnvironmentsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListEnvironmentsApiV2EnvironmentsGetResponses,
    ListEnvironmentsApiV2EnvironmentsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/environments",
    ...options,
  });

/**
 * Create Environment
 *
 * Create an environment. ``reserved=True`` and the ``h/`` namespace require H-employee privileges.
 */
export const createEnvironmentApiV2EnvironmentsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateEnvironmentApiV2EnvironmentsPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateEnvironmentApiV2EnvironmentsPostResponses,
    CreateEnvironmentApiV2EnvironmentsPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/environments",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Environment
 *
 * Delete by identifier. Reserved rows: H employee only.
 */
export const deleteEnvironmentApiV2EnvironmentsEnvIdentifierDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteEnvironmentApiV2EnvironmentsEnvIdentifierDeleteData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).delete<
    DeleteEnvironmentApiV2EnvironmentsEnvIdentifierDeleteResponses,
    DeleteEnvironmentApiV2EnvironmentsEnvIdentifierDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/environments/{env_identifier}",
    ...options,
  });

/**
 * Get Environment
 *
 * Fetch by identifier; 404 if not visible. ``:path`` so slash-containing ids round-trip.
 */
export const getEnvironmentApiV2EnvironmentsEnvIdentifierGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetEnvironmentApiV2EnvironmentsEnvIdentifierGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetEnvironmentApiV2EnvironmentsEnvIdentifierGetResponses,
    GetEnvironmentApiV2EnvironmentsEnvIdentifierGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/environments/{env_identifier}",
    ...options,
  });

/**
 * Update Environment
 *
 * Replace ``spec`` + ``description``. ``spec.id`` must match the URL identifier; renames are not supported.
 */
export const updateEnvironmentApiV2EnvironmentsEnvIdentifierPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateEnvironmentApiV2EnvironmentsEnvIdentifierPutData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).put<
    UpdateEnvironmentApiV2EnvironmentsEnvIdentifierPutResponses,
    UpdateEnvironmentApiV2EnvironmentsEnvIdentifierPutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/environments/{env_identifier}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Agents
 *
 * List reserved + caller's org agents.
 */
export const listAgentsApiV2AgentsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListAgentsApiV2AgentsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListAgentsApiV2AgentsGetResponses,
    ListAgentsApiV2AgentsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/agents",
    ...options,
  });

/**
 * Create Agent
 *
 * Create an agent. ``reserved=True`` and the ``h/`` namespace require H-employee privileges.
 */
export const createAgentApiV2AgentsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateAgentApiV2AgentsPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateAgentApiV2AgentsPostResponses,
    CreateAgentApiV2AgentsPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/agents",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Agent
 *
 * Delete by identifier. Reserved rows: H employee only.
 */
export const deleteAgentApiV2AgentsAgentIdentifierDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteAgentApiV2AgentsAgentIdentifierDeleteData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).delete<
    DeleteAgentApiV2AgentsAgentIdentifierDeleteResponses,
    DeleteAgentApiV2AgentsAgentIdentifierDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/agents/{agent_identifier}",
    ...options,
  });

/**
 * Get Agent
 *
 * Fetch by identifier; 404 if not visible. ``:path`` so slash-containing ids round-trip.
 */
export const getAgentApiV2AgentsAgentIdentifierGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetAgentApiV2AgentsAgentIdentifierGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetAgentApiV2AgentsAgentIdentifierGetResponses,
    GetAgentApiV2AgentsAgentIdentifierGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/agents/{agent_identifier}",
    ...options,
  });

/**
 * Update Agent
 *
 * Replace ``spec``. ``spec.name`` must match the URL identifier; renames are not supported.
 */
export const updateAgentApiV2AgentsAgentIdentifierPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateAgentApiV2AgentsAgentIdentifierPutData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpdateAgentApiV2AgentsAgentIdentifierPutResponses,
    UpdateAgentApiV2AgentsAgentIdentifierPutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/agents/{agent_identifier}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
