// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CancelSessionData,
  CancelSessionErrors,
  CancelSessionResponses,
  CreateAgentData,
  CreateAgentErrors,
  CreateAgentResponses,
  CreateEnvironmentData,
  CreateEnvironmentErrors,
  CreateEnvironmentResponses,
  CreateSessionData,
  CreateSessionErrors,
  CreateSessionResponses,
  CreateSkillData,
  CreateSkillErrors,
  CreateSkillResponses,
  DeleteAgentData,
  DeleteAgentErrors,
  DeleteAgentResponses,
  DeleteEnvironmentData,
  DeleteEnvironmentErrors,
  DeleteEnvironmentResponses,
  DeleteSkillData,
  DeleteSkillErrors,
  DeleteSkillResponses,
  ForceSessionAnswerData,
  ForceSessionAnswerErrors,
  ForceSessionAnswerResponses,
  GetAgentData,
  GetAgentErrors,
  GetAgentResponses,
  GetEnvironmentData,
  GetEnvironmentErrors,
  GetEnvironmentResponses,
  GetSessionChangesData,
  GetSessionChangesErrors,
  GetSessionChangesResponses,
  GetSessionData,
  GetSessionErrors,
  GetSessionQuotaData,
  GetSessionQuotaErrors,
  GetSessionQuotaResponses,
  GetSessionResourceData,
  GetSessionResourceErrors,
  GetSessionResourceResponses,
  GetSessionResponses,
  GetSessionStatusData,
  GetSessionStatusErrors,
  GetSessionStatusResponses,
  GetSkillData,
  GetSkillErrors,
  GetSkillResponses,
  ListAgentsData,
  ListAgentsErrors,
  ListAgentsResponses,
  ListEnvironmentsData,
  ListEnvironmentsErrors,
  ListEnvironmentsResponses,
  ListSessionEventsData,
  ListSessionEventsErrors,
  ListSessionEventsResponses,
  ListSessionsData,
  ListSessionsErrors,
  ListSessionsResponses,
  ListSkillsData,
  ListSkillsErrors,
  ListSkillsResponses,
  PauseSessionData,
  PauseSessionErrors,
  PauseSessionResponses,
  ResumeSessionData,
  ResumeSessionErrors,
  ResumeSessionResponses,
  SendSessionMessagesData,
  SendSessionMessagesErrors,
  SendSessionMessagesResponses,
  ShareSessionData,
  ShareSessionErrors,
  ShareSessionResponses,
  SubmitEventFeedbackData,
  SubmitEventFeedbackErrors,
  SubmitEventFeedbackResponses,
  SubmitSessionFeedbackData,
  SubmitSessionFeedbackErrors,
  SubmitSessionFeedbackResponses,
  UnshareSessionData,
  UnshareSessionErrors,
  UnshareSessionResponses,
  UpdateAgentData,
  UpdateAgentErrors,
  UpdateAgentResponses,
  UpdateEnvironmentData,
  UpdateEnvironmentErrors,
  UpdateEnvironmentResponses,
  UpdateSkillData,
  UpdateSkillErrors,
  UpdateSkillResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * List Sessions
 *
 * List sessions visible to ``user``.
 */
export const listSessions = <ThrowOnError extends boolean = false>(
  options?: Options<ListSessionsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListSessionsResponses,
    ListSessionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions",
    ...options,
  });

/**
 * Create Session
 *
 * Create an agentic session.
 *
 * Pass ``Idempotency-Key`` for safe retries: identical requests within 24h
 * return the original session; reuse with a different body returns 422.
 */
export const createSession = <ThrowOnError extends boolean = false>(
  options: Options<CreateSessionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateSessionResponses,
    CreateSessionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Session Quota
 *
 * Concurrent-session quota for the authenticated user.
 */
export const getSessionQuota = <ThrowOnError extends boolean = false>(
  options?: Options<GetSessionQuotaData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetSessionQuotaResponses,
    GetSessionQuotaErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/quota",
    ...options,
  });

/**
 * Cancel Session
 *
 * Cancel the session.
 */
export const cancelSession = <ThrowOnError extends boolean = false>(
  options: Options<CancelSessionData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    CancelSessionResponses,
    CancelSessionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}",
    ...options,
  });

/**
 * Get Session
 *
 * Get a session.
 */
export const getSession = <ThrowOnError extends boolean = false>(
  options: Options<GetSessionData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSessionResponses,
    GetSessionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}",
    ...options,
  });

/**
 * Get Session Status
 *
 * Get a session's live status.
 */
export const getSessionStatus = <ThrowOnError extends boolean = false>(
  options: Options<GetSessionStatusData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSessionStatusResponses,
    GetSessionStatusErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}/status",
    ...options,
  });

/**
 * Send Session Messages
 *
 * Send a user message (single or batch).
 */
export const sendSessionMessages = <ThrowOnError extends boolean = false>(
  options: Options<SendSessionMessagesData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    SendSessionMessagesResponses,
    SendSessionMessagesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}/messages",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Pause Session
 *
 * Pause the session.
 */
export const pauseSession = <ThrowOnError extends boolean = false>(
  options: Options<PauseSessionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PauseSessionResponses,
    PauseSessionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}/pause",
    ...options,
  });

/**
 * Resume Session
 *
 * Resume the session.
 */
export const resumeSession = <ThrowOnError extends boolean = false>(
  options: Options<ResumeSessionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ResumeSessionResponses,
    ResumeSessionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}/resume",
    ...options,
  });

/**
 * Force Session Answer
 *
 * Ask the agent to emit a final answer on its next step.
 */
export const forceSessionAnswer = <ThrowOnError extends boolean = false>(
  options: Options<ForceSessionAnswerData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ForceSessionAnswerResponses,
    ForceSessionAnswerErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}/force_answer",
    ...options,
  });

/**
 * Get Session Changes
 *
 * Long-poll for new events since ``from_index``; 204 if none arrive within ``wait_for_seconds``.
 */
export const getSessionChanges = <ThrowOnError extends boolean = false>(
  options: Options<GetSessionChangesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSessionChangesResponses,
    GetSessionChangesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}/changes",
    ...options,
  });

/**
 * List Session Events
 *
 * Paginated event history. Use ``/changes`` for live tailing.
 */
export const listSessionEvents = <ThrowOnError extends boolean = false>(
  options: Options<ListSessionEventsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ListSessionEventsResponses,
    ListSessionEventsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}/events",
    ...options,
  });

/**
 * Submit Session Feedback
 *
 * Record semantic-success feedback on the whole session.
 */
export const submitSessionFeedback = <ThrowOnError extends boolean = false>(
  options: Options<SubmitSessionFeedbackData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    SubmitSessionFeedbackResponses,
    SubmitSessionFeedbackErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}/feedback",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Submit Event Feedback
 *
 * Record feedback on a single event in the session's history.
 */
export const submitEventFeedback = <ThrowOnError extends boolean = false>(
  options: Options<SubmitEventFeedbackData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    SubmitEventFeedbackResponses,
    SubmitEventFeedbackErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}/events/{event_index}/feedback",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Unshare Session
 *
 * Revoke public access to the session.
 */
export const unshareSession = <ThrowOnError extends boolean = false>(
  options: Options<UnshareSessionData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    UnshareSessionResponses,
    UnshareSessionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}/share",
    ...options,
  });

/**
 * Share Session
 *
 * Make the session publicly readable; returns the share URL path.
 */
export const shareSession = <ThrowOnError extends boolean = false>(
  options: Options<ShareSessionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ShareSessionResponses,
    ShareSessionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}/share",
    ...options,
  });

/**
 * Get Session Resource
 *
 * Redirect to a presigned S3 URL for a session-owned resource.
 */
export const getSessionResource = <ThrowOnError extends boolean = false>(
  options: Options<GetSessionResourceData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSessionResourceResponses,
    GetSessionResourceErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/sessions/{id}/resources/{bucket}/{key}",
    ...options,
  });

/**
 * List Skills
 *
 * List reserved + caller's org skills, optionally filtered by name prefix.
 */
export const listSkills = <ThrowOnError extends boolean = false>(
  options?: Options<ListSkillsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListSkillsResponses,
    ListSkillsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/skills",
    ...options,
  });

/**
 * Create Skill
 *
 * Create a skill. The ``h/`` namespace is reserved for built-in skills.
 */
export const createSkill = <ThrowOnError extends boolean = false>(
  options: Options<CreateSkillData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateSkillResponses,
    CreateSkillErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/skills",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Skill
 *
 * Delete by name. Reserved rows: H employee only.
 */
export const deleteSkill = <ThrowOnError extends boolean = false>(
  options: Options<DeleteSkillData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteSkillResponses,
    DeleteSkillErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/skills/{name}",
    ...options,
  });

/**
 * Get Skill
 *
 * Fetch by name; 404 if not visible. ``:path`` so slash-containing names round-trip.
 */
export const getSkill = <ThrowOnError extends boolean = false>(
  options: Options<GetSkillData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSkillResponses,
    GetSkillErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/skills/{name}",
    ...options,
  });

/**
 * Update Skill
 *
 * Replace a skill's content. ``name`` must match the URL identifier; renames are not supported.
 */
export const updateSkill = <ThrowOnError extends boolean = false>(
  options: Options<UpdateSkillData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpdateSkillResponses,
    UpdateSkillErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/skills/{name}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Environments
 *
 * List reserved + caller's org environments.
 */
export const listEnvironments = <ThrowOnError extends boolean = false>(
  options?: Options<ListEnvironmentsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListEnvironmentsResponses,
    ListEnvironmentsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/environments",
    ...options,
  });

/**
 * Create Environment
 *
 * Create an environment.
 */
export const createEnvironment = <ThrowOnError extends boolean = false>(
  options: Options<CreateEnvironmentData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateEnvironmentResponses,
    CreateEnvironmentErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/environments",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Environment
 *
 * Delete by identifier. Reserved rows: H employee only.
 */
export const deleteEnvironment = <ThrowOnError extends boolean = false>(
  options: Options<DeleteEnvironmentData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteEnvironmentResponses,
    DeleteEnvironmentErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/environments/{id}",
    ...options,
  });

/**
 * Get Environment
 *
 * Fetch by identifier; 404 if not visible. ``:path`` so slash-containing ids round-trip.
 */
export const getEnvironment = <ThrowOnError extends boolean = false>(
  options: Options<GetEnvironmentData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEnvironmentResponses,
    GetEnvironmentErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/environments/{id}",
    ...options,
  });

/**
 * Update Environment
 *
 * Replace the environment spec.
 */
export const updateEnvironment = <ThrowOnError extends boolean = false>(
  options: Options<UpdateEnvironmentData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpdateEnvironmentResponses,
    UpdateEnvironmentErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/environments/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Agents
 *
 * List reserved + caller's org agents.
 */
export const listAgents = <ThrowOnError extends boolean = false>(
  options?: Options<ListAgentsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListAgentsResponses,
    ListAgentsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/agents",
    ...options,
  });

/**
 * Create Agent
 *
 * Create an agent..
 */
export const createAgent = <ThrowOnError extends boolean = false>(
  options: Options<CreateAgentData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateAgentResponses,
    CreateAgentErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/agents",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Agent
 *
 * Delete by identifier. Reserved rows: H employee only.
 */
export const deleteAgent = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAgentData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteAgentResponses,
    DeleteAgentErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/agents/{agent_name}",
    ...options,
  });

/**
 * Get Agent
 *
 * Fetch by identifier; 404 if not visible. ``:path`` so slash-containing ids round-trip.
 */
export const getAgent = <ThrowOnError extends boolean = false>(
  options: Options<GetAgentData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetAgentResponses,
    GetAgentErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/agents/{agent_name}",
    ...options,
  });

/**
 * Update Agent
 *
 * Replace ``spec``. ``spec.name`` must match the URL identifier; renames are not supported.
 */
export const updateAgent = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAgentData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpdateAgentResponses,
    UpdateAgentErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v2/agents/{agent_name}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
