// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8000" | (string & {});
};

/**
 * Agent
 *
 * Declarative agent definition.
 */
export type Agent = {
  /**
   * Name
   *
   * Unique catalog identifier for this agent. Format: lowercase ASCII letters, digits and hyphens; must start and end with alphanumeric; max 63 chars per segment; optional single 'org/' namespace prefix (e.g. 'h/web-environment').
   */
  name: string;
  /**
   * Description
   *
   * Short summary advertised to parent agents that may delegate to this one.
   */
  description: string;
  /**
   * Environments
   *
   * Environments the agent runs in. A string entry references a catalog id; an inline Environment defines an ad-hoc environment. At least one entry, at most one per kind.
   */
  environments: Array<
    | string
    | ({
        kind: "web";
      } & Browser)
    | ({
        kind: "code";
      } & CodeSandbox)
    | ({
        kind: "mcp";
      } & Mcp)
    | ({
        kind: "memory";
      } & Memory)
  >;
  /**
   * Model
   *
   * Model id; defaults to the platform-provided one if omitted.
   */
  model?: string | null;
  /**
   * Instructions
   *
   * Steering text appended to the system prompt.
   */
  instructions?: string | null;
  /**
   * Subagents
   *
   * Agents this one can spawn. A string entry references another catalog id; an inline Agent defines an ad-hoc sub-agent.
   */
  subagents?: Array<string | Agent> | null;
  /**
   * Skills
   *
   * Skills available to this agent. A string entry references a catalog id; an inline Skill defines an ad-hoc skill.
   */
  skills?: Array<string | Skill> | null;
};

/**
 * AgentRecord
 *
 * Catalog row exposing an ``Agent`` spec payload plus AgP metadata.
 *
 * The catalog handle is ``spec.name``; callers reference it directly
 * via ``record.spec.name`` rather than a duplicated top-level field.
 */
export type AgentRecord = {
  /**
   * Id
   */
  id: string;
  /**
   * Typed agent definition consumed by the runtime.
   */
  spec: Agent;
  /**
   * Reserved
   *
   * True for H-owned rows; world-readable, write-locked behind employee_only.
   */
  reserved: boolean;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
};

/**
 * Browser
 *
 * Browser environment.
 */
export type Browser = {
  /**
   * Id
   *
   * Catalog id.
   */
  id: string;
  /**
   * Kind
   */
  kind?: "web";
  /**
   * Headless
   *
   * Run without a visible window.
   */
  headless: boolean;
  /**
   * Width
   *
   * Viewport width in pixels.
   */
  width: number;
  /**
   * Height
   *
   * Viewport height in pixels.
   */
  height: number;
  /**
   * Start Url
   *
   * Initial URL.
   */
  start_url: string | null;
};

/**
 * CodeSandbox
 *
 * Code sandbox environment.
 */
export type CodeSandbox = {
  /**
   * Id
   *
   * Catalog id.
   */
  id: string;
  /**
   * Kind
   */
  kind?: "code";
  /**
   * Pip Packages
   *
   * Pip packages installed at provision time.
   */
  pip_packages?: Array<string>;
  /**
   * Env
   *
   * Environment variables.
   */
  env?: {
    [key: string]: string;
  };
  /**
   * Mcp Servers
   *
   * MCP servers reachable from the sandbox.
   */
  mcp_servers?: Array<McpServer>;
};

/**
 * CreateAgent
 *
 * ``POST /api/v2/agents`` body.
 */
export type CreateAgent = {
  /**
   * Typed agent definition consumed by the runtime.
   */
  spec: Agent;
  /**
   * Reserved
   *
   * H employees only; rejected with 403 otherwise.
   */
  reserved?: boolean;
};

/**
 * CreateEnvironment
 *
 * ``POST /api/v2/environments`` body.
 */
export type CreateEnvironment = {
  /**
   * Spec
   */
  spec:
    | ({
        kind: "web";
      } & Browser)
    | ({
        kind: "code";
      } & CodeSandbox)
    | ({
        kind: "mcp";
      } & Mcp)
    | ({
        kind: "memory";
      } & Memory);
  /**
   * Description
   */
  description?: string;
  /**
   * Reserved
   *
   * H employees only; rejected with 403 otherwise.
   */
  reserved?: boolean;
};

/**
 * CreateMemory
 *
 * Upsert a memory by ``(org_id, namespace, key)``.
 */
export type CreateMemory = {
  /**
   * Namespace
   */
  namespace: string;
  /**
   * Key
   */
  key: string;
  /**
   * Value
   */
  value: string;
};

/**
 * CreateSkill
 *
 * Request to create a skill.
 */
export type CreateSkill = {
  /**
   * Name
   *
   * Kebab-case stable handle the agent uses to reference this skill.
   */
  name: string;
  /**
   * Description
   *
   * One-line routing hint shown in the skill catalog.
   */
  description: string;
  /**
   * Body
   *
   * Markdown prompt fragment. Required unless `uri` is set.
   */
  body?: string;
  /**
   * Source
   *
   * Provenance URL.
   */
  source?: string | null;
  /**
   * Url Pattern
   *
   * Inject only when an observation URL matches this regex. Mutually exclusive with `uri`.
   */
  url_pattern?: string | null;
  /**
   * Uri
   *
   * Fetch body on demand from this location. Mutually exclusive with `url_pattern`.
   */
  uri?: string | null;
  /**
   * Reserved
   *
   * H employees only; rejected with 403 otherwise. Reserved rows are world-readable.
   */
  reserved?: boolean;
};

/**
 * EnvironmentRecord
 *
 * Catalog row exposing an ``Environment`` spec plus AgP metadata.
 *
 * The catalog handle is ``spec.id``; callers reference it directly via
 * ``record.spec.id`` rather than a duplicated top-level field.
 */
export type EnvironmentRecord = {
  /**
   * Id
   */
  id: string;
  /**
   * Spec
   *
   * Discriminated by ``kind``.
   */
  spec:
    | ({
        kind: "web";
      } & Browser)
    | ({
        kind: "code";
      } & CodeSandbox)
    | ({
        kind: "mcp";
      } & Mcp)
    | ({
        kind: "memory";
      } & Memory);
  /**
   * Description
   */
  description?: string;
  /**
   * Reserved
   *
   * True for H-owned rows; world-readable, write-locked behind employee_only.
   */
  reserved: boolean;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
};

/**
 * Feedback
 *
 * Feedback on the semantic success of the trajectory.
 */
export type Feedback = {
  /**
   * Success
   */
  success: boolean;
  /**
   * Message
   */
  message?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * MCP
 *
 * MCP environment.
 */
export type Mcp = {
  /**
   * Id
   *
   * Catalog id.
   */
  id: string;
  /**
   * Kind
   */
  kind?: "mcp";
  /**
   * Servers
   *
   * At least one MCP server.
   */
  servers: Array<McpServer>;
};

/**
 * MCPServer
 *
 * MCP server attached to an environment.
 */
export type McpServer = {
  /**
   * Name
   *
   * Stable identifier.
   */
  name: string;
  /**
   * Transport
   *
   * MCP transport.
   */
  transport: "stdio" | "streamable_http" | "sse";
  /**
   * Command
   *
   * Subprocess executable (stdio).
   */
  command?: string | null;
  /**
   * Args
   *
   * Subprocess argv tail (stdio).
   */
  args?: Array<string>;
  /**
   * Env
   *
   * Subprocess env vars (stdio).
   */
  env?: {
    [key: string]: string;
  };
  /**
   * Url
   *
   * Endpoint URL (HTTP).
   */
  url?: string | null;
  /**
   * Headers
   *
   * Request headers (HTTP).
   */
  headers?: {
    [key: string]: string;
  };
};

/**
 * Memory
 *
 * Cross-session key-value memory backed by AgP.
 */
export type Memory = {
  /**
   * Id
   *
   * Catalog id.
   */
  id: string;
  /**
   * Kind
   */
  kind?: "memory";
  /**
   * Namespace
   *
   * Memory namespace; scope for keys across sessions.
   */
  namespace: string;
};

/**
 * MemoryRecord
 *
 * Persistent KV entry scoped to ``(org_id, namespace, key)``.
 */
export type MemoryRecord = {
  /**
   * Id
   */
  id: string;
  /**
   * Namespace
   */
  namespace: string;
  /**
   * Key
   */
  key: string;
  /**
   * Value
   */
  value: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
};

/**
 * Metrics
 *
 * Metrics for a trajectory.
 */
export type Metrics = {
  /**
   * Steps
   */
  steps?: number;
  /**
   * Cost Per Model
   */
  cost_per_model?: Array<ModelCost>;
  /**
   * Input Cost
   */
  input_cost?: number | null;
  /**
   * Output Cost
   */
  output_cost?: number | null;
  /**
   * Reasoning Cost
   */
  reasoning_cost?: number | null;
  /**
   * Total Cost
   */
  total_cost?: number | null;
};

/**
 * ModelCost
 *
 * Cost for a model.
 */
export type ModelCost = {
  /**
   * Name
   */
  name: string;
  /**
   * Input Tokens
   */
  input_tokens: number;
  /**
   * Output Tokens
   */
  output_tokens: number;
  /**
   * Reasoning Tokens
   */
  reasoning_tokens: number;
  /**
   * Input Cost
   */
  input_cost?: number | null;
  /**
   * Output Cost
   */
  output_cost?: number | null;
  /**
   * Reasoning Cost
   */
  reasoning_cost?: number | null;
  /**
   * Total Cost
   */
  total_cost?: number | null;
};

/**
 * ModelUsage
 *
 * Per-model token usage.
 */
export type ModelUsage = {
  /**
   * Name
   */
  name: string;
  /**
   * Input Tokens
   */
  input_tokens: number;
  /**
   * Output Tokens
   */
  output_tokens: number;
  /**
   * Reasoning Tokens
   */
  reasoning_tokens: number;
};

/**
 * Page[AgentRecord]
 */
export type PageAgentRecord = {
  /**
   * Items
   */
  items: Array<AgentRecord>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
};

/**
 * Page[EnvironmentRecord]
 */
export type PageEnvironmentRecord = {
  /**
   * Items
   */
  items: Array<EnvironmentRecord>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
};

/**
 * Page[MemoryRecord]
 */
export type PageMemoryRecord = {
  /**
   * Items
   */
  items: Array<MemoryRecord>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
};

/**
 * Page[SessionSummary]
 */
export type PageSessionSummary = {
  /**
   * Items
   */
  items: Array<SessionSummary>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
};

/**
 * Page[SkillRecord]
 */
export type PageSkillRecord = {
  /**
   * Items
   */
  items: Array<SkillRecord>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
};

/**
 * Page[TrajectoryEvent]
 */
export type PageTrajectoryEvent = {
  /**
   * Items
   */
  items: Array<TrajectoryEvent>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
};

/**
 * QuotaStatus
 *
 * Quota status.
 */
export type QuotaStatus = {
  /**
   * Scope
   */
  scope: "user" | "org";
  /**
   * Limit
   */
  limit: number;
  /**
   * Active
   */
  active: number;
  /**
   * Available
   */
  available: number;
};

/**
 * Session
 *
 * Full session envelope: original request + live status.
 */
export type Session = {
  /**
   * Id
   */
  id: string;
  request: SessionRequest;
  status: SessionStatus;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Started At
   */
  started_at?: string | null;
  /**
   * Finished At
   */
  finished_at?: string | null;
};

/**
 * SessionRequest
 *
 * ``POST /api/v2/sessions`` body.
 */
export type SessionRequest = {
  /**
   * Agent
   *
   * Catalog id or inline Agent. Carries its own environments.
   */
  agent: string | Agent;
  /**
   * Messages
   *
   * Queued before turn 1. Accepts a string, a single UserMessageEvent, or a list.
   */
  messages?: string | UserMessageEvent | Array<UserMessageEvent> | null;
  /**
   * Max Steps
   *
   * Cap on policy calls; runtime default if null.
   */
  max_steps?: number | null;
  /**
   * Max Time S
   *
   * Cap on wall-clock seconds.
   */
  max_time_s?: number | null;
  /**
   * Idle Timeout S
   *
   * Idle window before auto-termination; null terminates on Answer.
   */
  idle_timeout_s?: number | null;
  /**
   * Group Id
   *
   * Group id for cascading and listing.
   */
  group_id?: string | null;
  /**
   * Parent Session Id
   *
   * Parent session id.
   */
  parent_session_id?: string | null;
};

/**
 * SessionStatus
 *
 * ``GET /api/v2/sessions/{id}/status`` response.
 */
export type SessionStatus = {
  status: TrajectoryStatus;
  /**
   * Error
   */
  error?: string | null;
  /**
   * Steps
   */
  steps?: number;
  /**
   * Usage Per Model
   */
  usage_per_model?: Array<ModelUsage>;
  /**
   * Subagent Session Ids
   */
  subagent_session_ids?: Array<string>;
};

/**
 * SessionSummary
 *
 * Flat projection for session listings.
 */
export type SessionSummary = {
  /**
   * Id
   */
  id: string;
  status: TrajectoryStatus;
  first_message?: UserMessageEvent | null;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Started At
   */
  started_at?: string | null;
  /**
   * Finished At
   */
  finished_at?: string | null;
};

/**
 * ShareLink
 *
 * Public share URL for a session.
 *
 * ``share_url`` is a path; clients prepend the AgP host. Today this points at the
 * v1 share router (``/share/api/v1/trajectories/{id}``); will migrate to
 * ``/share/v1/sessions/{id}`` once the v2 share router lands.
 */
export type ShareLink = {
  /**
   * Share Url
   */
  share_url: string;
};

/**
 * Skill
 *
 * Named instruction content. Loaded by name via ``load_skill`` or rendered inline by toolboxes.
 */
export type Skill = {
  /**
   * Name
   *
   * Catalog id. Format: lowercase ASCII letters, digits and hyphens; must start and end with alphanumeric; max 63 chars per segment; optional single 'org/' namespace prefix (e.g. 'h/web-environment').
   */
  name: string;
  /**
   * Description
   *
   * One-line routing hint.
   */
  description: string;
  /**
   * Body
   *
   * Markdown content.
   */
  body: string;
  /**
   * Source
   *
   * Provenance URL.
   */
  source?: string | null;
  /**
   * Url Pattern
   *
   * Informational regex hinting at URLs where this skill applies (not gated).
   */
  url_pattern?: string | null;
};

/**
 * SkillRecord
 *
 * Named prompt fragment loaded into an agent's system prompt.
 */
export type SkillRecord = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Body
   */
  body: string;
  /**
   * Source
   */
  source: string | null;
  /**
   * Url Pattern
   */
  url_pattern: string | null;
  /**
   * Uri
   */
  uri: string | null;
  /**
   * Reserved
   */
  reserved: boolean;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
};

/**
 * TrajectoryChanges
 *
 * Changes to a trajectory.
 *
 * This represents a batch of updates returned by the polling API
 * when checking for new events and status changes on a trajectory.
 *
 * Used to incrementally fetch new events without
 * re-downloading the entire trajectory history.
 *
 * Attributes:
 * status: Current status of the trajectory
 * started_at: When the trajectory started execution (None if not yet started)
 * finished_at: When the trajectory finished (None if still running)
 * error: Error message if trajectory failed (None if no error)
 * new_events: List of new events since the last poll (empty if no new events)
 * answer: Answer to the trajectory (None if not available)
 */
export type TrajectoryChanges = {
  status: TrajectoryStatus;
  /**
   * Started At
   */
  started_at?: string | null;
  /**
   * Finished At
   */
  finished_at?: string | null;
  /**
   * Error
   */
  error?: string | null;
  /**
   * New Events
   */
  new_events?: Array<TrajectoryEvent>;
  /**
   * Answer
   */
  answer?:
    | string
    | {
        [key: string]: unknown;
      }
    | null;
  metrics?: Metrics;
};

/**
 * TrajectoryEvent
 *
 * Event from a trajectory.
 *
 * Unified from agp_client and agent_platform.
 * Uses the richer agent_platform version with screenshot serialization.
 *
 * Events represent individual actions, observations, or state changes during
 * trajectory execution. They form a chronological log of everything that happened.
 *
 * Common event types:
 * - AgentStartedEvent: Agent begins execution
 * - AgentCompletionEvent: Agent finishes successfully
 * - AgentErrorEvent: Agent encounters an error
 * - AgentEvent: Generic wrapper for agent-emitted events (policy_event, tool_result, observation_event)
 * - LiveViewUrlEvent: Live view URL becomes available
 * - ChatMessageEvent: Agent sends a chat message
 *
 * Attributes:
 * type: The type/name of the event (e.g., "AgentStartedEvent", "AgentEvent")
 * data: Event-specific data payload (structure varies by event type)
 * timestamp: When the event occurred
 */
export type TrajectoryEvent = {
  /**
   * Type
   */
  type: string;
  /**
   * Data
   */
  data: unknown;
  /**
   * Timestamp
   */
  timestamp: string;
};

/**
 * TrajectoryStatus
 *
 * State of a session/trajectory.
 *
 * Lifecycle::
 *
 * PENDING → RUNNING → {COMPLETED, FAILED, TIMED_OUT, INTERRUPTED}
 * |        ↑  ↑
 * |        |  └─────→ IDLE (interactive: agent waiting for next task)
 * |        ↓
 * └─────→ PAUSED
 */
export type TrajectoryStatus =
  | "pending"
  | "running"
  | "paused"
  | "idle"
  | "completed"
  | "failed"
  | "timed_out"
  | "interrupted";

/**
 * UpdateAgent
 *
 * ``PUT /api/v2/agents/{agent_identifier}`` body. Full replace; ``spec.name`` is immutable.
 */
export type UpdateAgent = {
  /**
   * Typed agent definition consumed by the runtime.
   */
  spec: Agent;
};

/**
 * UpdateEnvironment
 *
 * ``PUT /api/v2/environments/{env_identifier}`` body. Full replace; ``spec.id`` is immutable.
 */
export type UpdateEnvironment = {
  /**
   * Spec
   */
  spec:
    | ({
        kind: "web";
      } & Browser)
    | ({
        kind: "code";
      } & CodeSandbox)
    | ({
        kind: "mcp";
      } & Mcp)
    | ({
        kind: "memory";
      } & Memory);
  /**
   * Description
   */
  description?: string;
};

/**
 * UpdateMemory
 *
 * Update a memory's value in place.
 */
export type UpdateMemory = {
  /**
   * Value
   */
  value: string;
};

/**
 * UpdateSkill
 *
 * Request to update a skill. Full replacement; `name` is immutable.
 */
export type UpdateSkill = {
  /**
   * Description
   */
  description: string;
  /**
   * Body
   */
  body?: string;
  /**
   * Source
   */
  source?: string | null;
  /**
   * Url Pattern
   */
  url_pattern?: string | null;
  /**
   * Uri
   */
  uri?: string | null;
};

/**
 * UserMessageBatch
 *
 * Batch of user messages.
 */
export type UserMessageBatch = {
  /**
   * Type
   */
  type?: "batch";
  /**
   * Messages
   */
  messages: Array<UserMessageEvent>;
};

/**
 * UserMessageEvent
 *
 * The user is sending a message to an active agent.
 */
export type UserMessageEvent = {
  /**
   * Type
   */
  type?: "user_message";
  /**
   * Message
   */
  message: string;
  /**
   * Images
   */
  images?: Array<string>;
  /**
   * Caller Id
   */
  caller_id?: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

export type ListSessionsApiV2SessionsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Owner
     */
    owner?: "me" | "me-in-organization" | "organization" | "me-or-organization";
    /**
     * Status
     */
    status?: Array<TrajectoryStatus> | null;
    /**
     * Agent
     */
    agent?: Array<string> | null;
    /**
     * Group Id
     */
    group_id?: string | null;
    /**
     * Parent Session Id
     */
    parent_session_id?: string | null;
    /**
     * Page
     *
     * Page number (1-based)
     */
    page?: number;
    /**
     * Size
     *
     * Number of items per page
     */
    size?: number;
    /**
     * Sort
     *
     * Sort by field
     */
    sort?: "created_at" | "-created_at";
  };
  url: "/api/v2/sessions";
};

export type ListSessionsApiV2SessionsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListSessionsApiV2SessionsGetError =
  ListSessionsApiV2SessionsGetErrors[keyof ListSessionsApiV2SessionsGetErrors];

export type ListSessionsApiV2SessionsGetResponses = {
  /**
   * Successful Response
   */
  200: PageSessionSummary;
};

export type ListSessionsApiV2SessionsGetResponse =
  ListSessionsApiV2SessionsGetResponses[keyof ListSessionsApiV2SessionsGetResponses];

export type CreateSessionApiV2SessionsPostData = {
  body: SessionRequest;
  headers?: {
    /**
     * Idempotency-Key
     */
    "Idempotency-Key"?: string | null;
  };
  path?: never;
  query?: never;
  url: "/api/v2/sessions";
};

export type CreateSessionApiV2SessionsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateSessionApiV2SessionsPostError =
  CreateSessionApiV2SessionsPostErrors[keyof CreateSessionApiV2SessionsPostErrors];

export type CreateSessionApiV2SessionsPostResponses = {
  /**
   * Successful Response
   */
  201: Session;
};

export type CreateSessionApiV2SessionsPostResponse =
  CreateSessionApiV2SessionsPostResponses[keyof CreateSessionApiV2SessionsPostResponses];

export type GetSessionQuotaApiV2SessionsQuotaGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v2/sessions/quota";
};

export type GetSessionQuotaApiV2SessionsQuotaGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetSessionQuotaApiV2SessionsQuotaGetError =
  GetSessionQuotaApiV2SessionsQuotaGetErrors[keyof GetSessionQuotaApiV2SessionsQuotaGetErrors];

export type GetSessionQuotaApiV2SessionsQuotaGetResponses = {
  /**
   * Successful Response
   */
  200: QuotaStatus;
};

export type GetSessionQuotaApiV2SessionsQuotaGetResponse =
  GetSessionQuotaApiV2SessionsQuotaGetResponses[keyof GetSessionQuotaApiV2SessionsQuotaGetResponses];

export type CancelSessionApiV2SessionsIdDeleteData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v2/sessions/{id}";
};

export type CancelSessionApiV2SessionsIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CancelSessionApiV2SessionsIdDeleteError =
  CancelSessionApiV2SessionsIdDeleteErrors[keyof CancelSessionApiV2SessionsIdDeleteErrors];

export type CancelSessionApiV2SessionsIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type CancelSessionApiV2SessionsIdDeleteResponse =
  CancelSessionApiV2SessionsIdDeleteResponses[keyof CancelSessionApiV2SessionsIdDeleteResponses];

export type GetSessionApiV2SessionsIdGetData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v2/sessions/{id}";
};

export type GetSessionApiV2SessionsIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetSessionApiV2SessionsIdGetError =
  GetSessionApiV2SessionsIdGetErrors[keyof GetSessionApiV2SessionsIdGetErrors];

export type GetSessionApiV2SessionsIdGetResponses = {
  /**
   * Successful Response
   */
  200: Session;
};

export type GetSessionApiV2SessionsIdGetResponse =
  GetSessionApiV2SessionsIdGetResponses[keyof GetSessionApiV2SessionsIdGetResponses];

export type GetSessionStatusApiV2SessionsIdStatusGetData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v2/sessions/{id}/status";
};

export type GetSessionStatusApiV2SessionsIdStatusGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetSessionStatusApiV2SessionsIdStatusGetError =
  GetSessionStatusApiV2SessionsIdStatusGetErrors[keyof GetSessionStatusApiV2SessionsIdStatusGetErrors];

export type GetSessionStatusApiV2SessionsIdStatusGetResponses = {
  /**
   * Successful Response
   */
  200: SessionStatus;
};

export type GetSessionStatusApiV2SessionsIdStatusGetResponse =
  GetSessionStatusApiV2SessionsIdStatusGetResponses[keyof GetSessionStatusApiV2SessionsIdStatusGetResponses];

export type SendSessionMessagesApiV2SessionsIdMessagesPostData = {
  /**
   * Input
   */
  body:
    | ({
        type: "user_message";
      } & UserMessageEvent)
    | ({
        type: "batch";
      } & UserMessageBatch);
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v2/sessions/{id}/messages";
};

export type SendSessionMessagesApiV2SessionsIdMessagesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SendSessionMessagesApiV2SessionsIdMessagesPostError =
  SendSessionMessagesApiV2SessionsIdMessagesPostErrors[keyof SendSessionMessagesApiV2SessionsIdMessagesPostErrors];

export type SendSessionMessagesApiV2SessionsIdMessagesPostResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type PauseSessionApiV2SessionsIdPausePostData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v2/sessions/{id}/pause";
};

export type PauseSessionApiV2SessionsIdPausePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PauseSessionApiV2SessionsIdPausePostError =
  PauseSessionApiV2SessionsIdPausePostErrors[keyof PauseSessionApiV2SessionsIdPausePostErrors];

export type PauseSessionApiV2SessionsIdPausePostResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type ResumeSessionApiV2SessionsIdResumePostData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v2/sessions/{id}/resume";
};

export type ResumeSessionApiV2SessionsIdResumePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResumeSessionApiV2SessionsIdResumePostError =
  ResumeSessionApiV2SessionsIdResumePostErrors[keyof ResumeSessionApiV2SessionsIdResumePostErrors];

export type ResumeSessionApiV2SessionsIdResumePostResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type ForceSessionAnswerApiV2SessionsIdForceAnswerPostData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v2/sessions/{id}/force_answer";
};

export type ForceSessionAnswerApiV2SessionsIdForceAnswerPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ForceSessionAnswerApiV2SessionsIdForceAnswerPostError =
  ForceSessionAnswerApiV2SessionsIdForceAnswerPostErrors[keyof ForceSessionAnswerApiV2SessionsIdForceAnswerPostErrors];

export type ForceSessionAnswerApiV2SessionsIdForceAnswerPostResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type GetSessionChangesApiV2SessionsIdChangesGetData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: {
    /**
     * From Index
     */
    from_index?: number;
    /**
     * Limit
     */
    limit?: number | null;
    /**
     * Include Events
     */
    include_events?: boolean;
    /**
     * Wait For Seconds
     */
    wait_for_seconds?: number;
  };
  url: "/api/v2/sessions/{id}/changes";
};

export type GetSessionChangesApiV2SessionsIdChangesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetSessionChangesApiV2SessionsIdChangesGetError =
  GetSessionChangesApiV2SessionsIdChangesGetErrors[keyof GetSessionChangesApiV2SessionsIdChangesGetErrors];

export type GetSessionChangesApiV2SessionsIdChangesGetResponses = {
  /**
   * Successful Response
   */
  200: TrajectoryChanges;
  /**
   * No changes since the specified index
   */
  204: void;
};

export type GetSessionChangesApiV2SessionsIdChangesGetResponse =
  GetSessionChangesApiV2SessionsIdChangesGetResponses[keyof GetSessionChangesApiV2SessionsIdChangesGetResponses];

export type ListSessionEventsApiV2SessionsIdEventsGetData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: {
    /**
     * Page
     */
    page?: number;
    /**
     * Size
     */
    size?: number;
    /**
     * Sort
     */
    sort?: Array<"timestamp" | "-timestamp"> | null;
    /**
     * Type
     */
    type?: string | null;
  };
  url: "/api/v2/sessions/{id}/events";
};

export type ListSessionEventsApiV2SessionsIdEventsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListSessionEventsApiV2SessionsIdEventsGetError =
  ListSessionEventsApiV2SessionsIdEventsGetErrors[keyof ListSessionEventsApiV2SessionsIdEventsGetErrors];

export type ListSessionEventsApiV2SessionsIdEventsGetResponses = {
  /**
   * Successful Response
   */
  200: PageTrajectoryEvent;
};

export type ListSessionEventsApiV2SessionsIdEventsGetResponse =
  ListSessionEventsApiV2SessionsIdEventsGetResponses[keyof ListSessionEventsApiV2SessionsIdEventsGetResponses];

export type SubmitSessionFeedbackApiV2SessionsIdFeedbackPostData = {
  body: Feedback;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v2/sessions/{id}/feedback";
};

export type SubmitSessionFeedbackApiV2SessionsIdFeedbackPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SubmitSessionFeedbackApiV2SessionsIdFeedbackPostError =
  SubmitSessionFeedbackApiV2SessionsIdFeedbackPostErrors[keyof SubmitSessionFeedbackApiV2SessionsIdFeedbackPostErrors];

export type SubmitSessionFeedbackApiV2SessionsIdFeedbackPostResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type SubmitSessionFeedbackApiV2SessionsIdFeedbackPostResponse =
  SubmitSessionFeedbackApiV2SessionsIdFeedbackPostResponses[keyof SubmitSessionFeedbackApiV2SessionsIdFeedbackPostResponses];

export type SubmitEventFeedbackApiV2SessionsIdEventsEventIndexFeedbackPutData =
  {
    body: Feedback;
    path: {
      /**
       * Id
       */
      id: string;
      /**
       * Event Index
       */
      event_index: number;
    };
    query?: never;
    url: "/api/v2/sessions/{id}/events/{event_index}/feedback";
  };

export type SubmitEventFeedbackApiV2SessionsIdEventsEventIndexFeedbackPutErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type SubmitEventFeedbackApiV2SessionsIdEventsEventIndexFeedbackPutError =
  SubmitEventFeedbackApiV2SessionsIdEventsEventIndexFeedbackPutErrors[keyof SubmitEventFeedbackApiV2SessionsIdEventsEventIndexFeedbackPutErrors];

export type SubmitEventFeedbackApiV2SessionsIdEventsEventIndexFeedbackPutResponses =
  {
    /**
     * Successful Response
     */
    204: void;
  };

export type SubmitEventFeedbackApiV2SessionsIdEventsEventIndexFeedbackPutResponse =
  SubmitEventFeedbackApiV2SessionsIdEventsEventIndexFeedbackPutResponses[keyof SubmitEventFeedbackApiV2SessionsIdEventsEventIndexFeedbackPutResponses];

export type UnshareSessionApiV2SessionsIdShareDeleteData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v2/sessions/{id}/share";
};

export type UnshareSessionApiV2SessionsIdShareDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UnshareSessionApiV2SessionsIdShareDeleteError =
  UnshareSessionApiV2SessionsIdShareDeleteErrors[keyof UnshareSessionApiV2SessionsIdShareDeleteErrors];

export type UnshareSessionApiV2SessionsIdShareDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type UnshareSessionApiV2SessionsIdShareDeleteResponse =
  UnshareSessionApiV2SessionsIdShareDeleteResponses[keyof UnshareSessionApiV2SessionsIdShareDeleteResponses];

export type ShareSessionApiV2SessionsIdSharePostData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v2/sessions/{id}/share";
};

export type ShareSessionApiV2SessionsIdSharePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ShareSessionApiV2SessionsIdSharePostError =
  ShareSessionApiV2SessionsIdSharePostErrors[keyof ShareSessionApiV2SessionsIdSharePostErrors];

export type ShareSessionApiV2SessionsIdSharePostResponses = {
  /**
   * Successful Response
   */
  200: ShareLink;
};

export type ShareSessionApiV2SessionsIdSharePostResponse =
  ShareSessionApiV2SessionsIdSharePostResponses[keyof ShareSessionApiV2SessionsIdSharePostResponses];

export type GetSessionResourceApiV2SessionsIdResourcesBucketKeyGetData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
    /**
     * Bucket
     */
    bucket: string;
    /**
     * Key
     */
    key: string;
  };
  query?: never;
  url: "/api/v2/sessions/{id}/resources/{bucket}/{key}";
};

export type GetSessionResourceApiV2SessionsIdResourcesBucketKeyGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetSessionResourceApiV2SessionsIdResourcesBucketKeyGetError =
  GetSessionResourceApiV2SessionsIdResourcesBucketKeyGetErrors[keyof GetSessionResourceApiV2SessionsIdResourcesBucketKeyGetErrors];

export type GetSessionResourceApiV2SessionsIdResourcesBucketKeyGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListMemoriesApiV2MemoriesGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Namespace
     *
     * Exact namespace filter.
     */
    namespace?: string | null;
    /**
     * Key
     *
     * Key prefix filter.
     */
    key?: string | null;
    /**
     * Page
     *
     * Page number (1-based)
     */
    page?: number;
    /**
     * Size
     *
     * Number of items per page
     */
    size?: number;
    /**
     * Sort
     *
     * Sort by field
     */
    sort?: "updated_at" | "-updated_at";
  };
  url: "/api/v2/memories";
};

export type ListMemoriesApiV2MemoriesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListMemoriesApiV2MemoriesGetError =
  ListMemoriesApiV2MemoriesGetErrors[keyof ListMemoriesApiV2MemoriesGetErrors];

export type ListMemoriesApiV2MemoriesGetResponses = {
  /**
   * Successful Response
   */
  200: PageMemoryRecord;
};

export type ListMemoriesApiV2MemoriesGetResponse =
  ListMemoriesApiV2MemoriesGetResponses[keyof ListMemoriesApiV2MemoriesGetResponses];

export type CreateMemoryApiV2MemoriesPostData = {
  body: CreateMemory;
  path?: never;
  query?: never;
  url: "/api/v2/memories";
};

export type CreateMemoryApiV2MemoriesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateMemoryApiV2MemoriesPostError =
  CreateMemoryApiV2MemoriesPostErrors[keyof CreateMemoryApiV2MemoriesPostErrors];

export type CreateMemoryApiV2MemoriesPostResponses = {
  /**
   * Existing memory updated (upsert).
   */
  200: MemoryRecord;
  /**
   * New memory created.
   */
  201: unknown;
};

export type CreateMemoryApiV2MemoriesPostResponse =
  CreateMemoryApiV2MemoriesPostResponses[keyof CreateMemoryApiV2MemoriesPostResponses];

export type DeleteMemoryApiV2MemoriesIdDeleteData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v2/memories/{id}";
};

export type DeleteMemoryApiV2MemoriesIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteMemoryApiV2MemoriesIdDeleteError =
  DeleteMemoryApiV2MemoriesIdDeleteErrors[keyof DeleteMemoryApiV2MemoriesIdDeleteErrors];

export type DeleteMemoryApiV2MemoriesIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteMemoryApiV2MemoriesIdDeleteResponse =
  DeleteMemoryApiV2MemoriesIdDeleteResponses[keyof DeleteMemoryApiV2MemoriesIdDeleteResponses];

export type GetMemoryApiV2MemoriesIdGetData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v2/memories/{id}";
};

export type GetMemoryApiV2MemoriesIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetMemoryApiV2MemoriesIdGetError =
  GetMemoryApiV2MemoriesIdGetErrors[keyof GetMemoryApiV2MemoriesIdGetErrors];

export type GetMemoryApiV2MemoriesIdGetResponses = {
  /**
   * Successful Response
   */
  200: MemoryRecord;
};

export type GetMemoryApiV2MemoriesIdGetResponse =
  GetMemoryApiV2MemoriesIdGetResponses[keyof GetMemoryApiV2MemoriesIdGetResponses];

export type UpdateMemoryApiV2MemoriesIdPutData = {
  body: UpdateMemory;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v2/memories/{id}";
};

export type UpdateMemoryApiV2MemoriesIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateMemoryApiV2MemoriesIdPutError =
  UpdateMemoryApiV2MemoriesIdPutErrors[keyof UpdateMemoryApiV2MemoriesIdPutErrors];

export type UpdateMemoryApiV2MemoriesIdPutResponses = {
  /**
   * Successful Response
   */
  200: MemoryRecord;
};

export type UpdateMemoryApiV2MemoriesIdPutResponse =
  UpdateMemoryApiV2MemoriesIdPutResponses[keyof UpdateMemoryApiV2MemoriesIdPutResponses];

export type ListSkillsApiV2SkillsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Name
     *
     * Filter by name prefix.
     */
    name?: string | null;
    /**
     * Page
     *
     * Page number (1-based)
     */
    page?: number;
    /**
     * Size
     *
     * Number of items per page
     */
    size?: number;
    /**
     * Sort
     *
     * Sort by field
     */
    sort?: "created_at" | "-created_at" | "name" | "-name";
  };
  url: "/api/v2/skills";
};

export type ListSkillsApiV2SkillsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListSkillsApiV2SkillsGetError =
  ListSkillsApiV2SkillsGetErrors[keyof ListSkillsApiV2SkillsGetErrors];

export type ListSkillsApiV2SkillsGetResponses = {
  /**
   * Successful Response
   */
  200: PageSkillRecord;
};

export type ListSkillsApiV2SkillsGetResponse =
  ListSkillsApiV2SkillsGetResponses[keyof ListSkillsApiV2SkillsGetResponses];

export type CreateSkillApiV2SkillsPostData = {
  body: CreateSkill;
  path?: never;
  query?: never;
  url: "/api/v2/skills";
};

export type CreateSkillApiV2SkillsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateSkillApiV2SkillsPostError =
  CreateSkillApiV2SkillsPostErrors[keyof CreateSkillApiV2SkillsPostErrors];

export type CreateSkillApiV2SkillsPostResponses = {
  /**
   * Successful Response
   */
  201: SkillRecord;
};

export type CreateSkillApiV2SkillsPostResponse =
  CreateSkillApiV2SkillsPostResponses[keyof CreateSkillApiV2SkillsPostResponses];

export type DeleteSkillApiV2SkillsIdDeleteData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v2/skills/{id}";
};

export type DeleteSkillApiV2SkillsIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteSkillApiV2SkillsIdDeleteError =
  DeleteSkillApiV2SkillsIdDeleteErrors[keyof DeleteSkillApiV2SkillsIdDeleteErrors];

export type DeleteSkillApiV2SkillsIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteSkillApiV2SkillsIdDeleteResponse =
  DeleteSkillApiV2SkillsIdDeleteResponses[keyof DeleteSkillApiV2SkillsIdDeleteResponses];

export type GetSkillApiV2SkillsIdGetData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v2/skills/{id}";
};

export type GetSkillApiV2SkillsIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetSkillApiV2SkillsIdGetError =
  GetSkillApiV2SkillsIdGetErrors[keyof GetSkillApiV2SkillsIdGetErrors];

export type GetSkillApiV2SkillsIdGetResponses = {
  /**
   * Successful Response
   */
  200: SkillRecord;
};

export type GetSkillApiV2SkillsIdGetResponse =
  GetSkillApiV2SkillsIdGetResponses[keyof GetSkillApiV2SkillsIdGetResponses];

export type UpdateSkillApiV2SkillsIdPutData = {
  body: UpdateSkill;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v2/skills/{id}";
};

export type UpdateSkillApiV2SkillsIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateSkillApiV2SkillsIdPutError =
  UpdateSkillApiV2SkillsIdPutErrors[keyof UpdateSkillApiV2SkillsIdPutErrors];

export type UpdateSkillApiV2SkillsIdPutResponses = {
  /**
   * Successful Response
   */
  200: SkillRecord;
};

export type UpdateSkillApiV2SkillsIdPutResponse =
  UpdateSkillApiV2SkillsIdPutResponses[keyof UpdateSkillApiV2SkillsIdPutResponses];

export type ListEnvironmentsApiV2EnvironmentsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     *
     * Page number (1-based)
     */
    page?: number;
    /**
     * Size
     *
     * Number of items per page
     */
    size?: number;
    /**
     * Sort
     *
     * Sort by field
     */
    sort?: "created_at" | "-created_at" | "env_identifier" | "-env_identifier";
  };
  url: "/api/v2/environments";
};

export type ListEnvironmentsApiV2EnvironmentsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListEnvironmentsApiV2EnvironmentsGetError =
  ListEnvironmentsApiV2EnvironmentsGetErrors[keyof ListEnvironmentsApiV2EnvironmentsGetErrors];

export type ListEnvironmentsApiV2EnvironmentsGetResponses = {
  /**
   * Successful Response
   */
  200: PageEnvironmentRecord;
};

export type ListEnvironmentsApiV2EnvironmentsGetResponse =
  ListEnvironmentsApiV2EnvironmentsGetResponses[keyof ListEnvironmentsApiV2EnvironmentsGetResponses];

export type CreateEnvironmentApiV2EnvironmentsPostData = {
  body: CreateEnvironment;
  path?: never;
  query?: never;
  url: "/api/v2/environments";
};

export type CreateEnvironmentApiV2EnvironmentsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateEnvironmentApiV2EnvironmentsPostError =
  CreateEnvironmentApiV2EnvironmentsPostErrors[keyof CreateEnvironmentApiV2EnvironmentsPostErrors];

export type CreateEnvironmentApiV2EnvironmentsPostResponses = {
  /**
   * Successful Response
   */
  201: EnvironmentRecord;
};

export type CreateEnvironmentApiV2EnvironmentsPostResponse =
  CreateEnvironmentApiV2EnvironmentsPostResponses[keyof CreateEnvironmentApiV2EnvironmentsPostResponses];

export type DeleteEnvironmentApiV2EnvironmentsEnvIdentifierDeleteData = {
  body?: never;
  path: {
    /**
     * Env Identifier
     */
    env_identifier: string;
  };
  query?: never;
  url: "/api/v2/environments/{env_identifier}";
};

export type DeleteEnvironmentApiV2EnvironmentsEnvIdentifierDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteEnvironmentApiV2EnvironmentsEnvIdentifierDeleteError =
  DeleteEnvironmentApiV2EnvironmentsEnvIdentifierDeleteErrors[keyof DeleteEnvironmentApiV2EnvironmentsEnvIdentifierDeleteErrors];

export type DeleteEnvironmentApiV2EnvironmentsEnvIdentifierDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteEnvironmentApiV2EnvironmentsEnvIdentifierDeleteResponse =
  DeleteEnvironmentApiV2EnvironmentsEnvIdentifierDeleteResponses[keyof DeleteEnvironmentApiV2EnvironmentsEnvIdentifierDeleteResponses];

export type GetEnvironmentApiV2EnvironmentsEnvIdentifierGetData = {
  body?: never;
  path: {
    /**
     * Env Identifier
     */
    env_identifier: string;
  };
  query?: never;
  url: "/api/v2/environments/{env_identifier}";
};

export type GetEnvironmentApiV2EnvironmentsEnvIdentifierGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetEnvironmentApiV2EnvironmentsEnvIdentifierGetError =
  GetEnvironmentApiV2EnvironmentsEnvIdentifierGetErrors[keyof GetEnvironmentApiV2EnvironmentsEnvIdentifierGetErrors];

export type GetEnvironmentApiV2EnvironmentsEnvIdentifierGetResponses = {
  /**
   * Successful Response
   */
  200: EnvironmentRecord;
};

export type GetEnvironmentApiV2EnvironmentsEnvIdentifierGetResponse =
  GetEnvironmentApiV2EnvironmentsEnvIdentifierGetResponses[keyof GetEnvironmentApiV2EnvironmentsEnvIdentifierGetResponses];

export type UpdateEnvironmentApiV2EnvironmentsEnvIdentifierPutData = {
  body: UpdateEnvironment;
  path: {
    /**
     * Env Identifier
     */
    env_identifier: string;
  };
  query?: never;
  url: "/api/v2/environments/{env_identifier}";
};

export type UpdateEnvironmentApiV2EnvironmentsEnvIdentifierPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateEnvironmentApiV2EnvironmentsEnvIdentifierPutError =
  UpdateEnvironmentApiV2EnvironmentsEnvIdentifierPutErrors[keyof UpdateEnvironmentApiV2EnvironmentsEnvIdentifierPutErrors];

export type UpdateEnvironmentApiV2EnvironmentsEnvIdentifierPutResponses = {
  /**
   * Successful Response
   */
  200: EnvironmentRecord;
};

export type UpdateEnvironmentApiV2EnvironmentsEnvIdentifierPutResponse =
  UpdateEnvironmentApiV2EnvironmentsEnvIdentifierPutResponses[keyof UpdateEnvironmentApiV2EnvironmentsEnvIdentifierPutResponses];

export type ListAgentsApiV2AgentsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     *
     * Page number (1-based)
     */
    page?: number;
    /**
     * Size
     *
     * Number of items per page
     */
    size?: number;
    /**
     * Sort
     *
     * Sort by field
     */
    sort?:
      | "created_at"
      | "-created_at"
      | "agent_identifier"
      | "-agent_identifier";
  };
  url: "/api/v2/agents";
};

export type ListAgentsApiV2AgentsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListAgentsApiV2AgentsGetError =
  ListAgentsApiV2AgentsGetErrors[keyof ListAgentsApiV2AgentsGetErrors];

export type ListAgentsApiV2AgentsGetResponses = {
  /**
   * Successful Response
   */
  200: PageAgentRecord;
};

export type ListAgentsApiV2AgentsGetResponse =
  ListAgentsApiV2AgentsGetResponses[keyof ListAgentsApiV2AgentsGetResponses];

export type CreateAgentApiV2AgentsPostData = {
  body: CreateAgent;
  path?: never;
  query?: never;
  url: "/api/v2/agents";
};

export type CreateAgentApiV2AgentsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateAgentApiV2AgentsPostError =
  CreateAgentApiV2AgentsPostErrors[keyof CreateAgentApiV2AgentsPostErrors];

export type CreateAgentApiV2AgentsPostResponses = {
  /**
   * Successful Response
   */
  201: AgentRecord;
};

export type CreateAgentApiV2AgentsPostResponse =
  CreateAgentApiV2AgentsPostResponses[keyof CreateAgentApiV2AgentsPostResponses];

export type DeleteAgentApiV2AgentsAgentIdentifierDeleteData = {
  body?: never;
  path: {
    /**
     * Agent Identifier
     */
    agent_identifier: string;
  };
  query?: never;
  url: "/api/v2/agents/{agent_identifier}";
};

export type DeleteAgentApiV2AgentsAgentIdentifierDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteAgentApiV2AgentsAgentIdentifierDeleteError =
  DeleteAgentApiV2AgentsAgentIdentifierDeleteErrors[keyof DeleteAgentApiV2AgentsAgentIdentifierDeleteErrors];

export type DeleteAgentApiV2AgentsAgentIdentifierDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteAgentApiV2AgentsAgentIdentifierDeleteResponse =
  DeleteAgentApiV2AgentsAgentIdentifierDeleteResponses[keyof DeleteAgentApiV2AgentsAgentIdentifierDeleteResponses];

export type GetAgentApiV2AgentsAgentIdentifierGetData = {
  body?: never;
  path: {
    /**
     * Agent Identifier
     */
    agent_identifier: string;
  };
  query?: never;
  url: "/api/v2/agents/{agent_identifier}";
};

export type GetAgentApiV2AgentsAgentIdentifierGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetAgentApiV2AgentsAgentIdentifierGetError =
  GetAgentApiV2AgentsAgentIdentifierGetErrors[keyof GetAgentApiV2AgentsAgentIdentifierGetErrors];

export type GetAgentApiV2AgentsAgentIdentifierGetResponses = {
  /**
   * Successful Response
   */
  200: AgentRecord;
};

export type GetAgentApiV2AgentsAgentIdentifierGetResponse =
  GetAgentApiV2AgentsAgentIdentifierGetResponses[keyof GetAgentApiV2AgentsAgentIdentifierGetResponses];

export type UpdateAgentApiV2AgentsAgentIdentifierPutData = {
  body: UpdateAgent;
  path: {
    /**
     * Agent Identifier
     */
    agent_identifier: string;
  };
  query?: never;
  url: "/api/v2/agents/{agent_identifier}";
};

export type UpdateAgentApiV2AgentsAgentIdentifierPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateAgentApiV2AgentsAgentIdentifierPutError =
  UpdateAgentApiV2AgentsAgentIdentifierPutErrors[keyof UpdateAgentApiV2AgentsAgentIdentifierPutErrors];

export type UpdateAgentApiV2AgentsAgentIdentifierPutResponses = {
  /**
   * Successful Response
   */
  200: AgentRecord;
};

export type UpdateAgentApiV2AgentsAgentIdentifierPutResponse =
  UpdateAgentApiV2AgentsAgentIdentifierPutResponses[keyof UpdateAgentApiV2AgentsAgentIdentifierPutResponses];
