// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../api/index.js";
import type * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { PauseSchedule } from "../../../types/PauseSchedule.js";

export const Request: core.serialization.Schema<
    serializers.schedules.pauseSchedule.Request.Raw,
    HaiAgents.PauseSchedule | null
> = PauseSchedule.nullable();

export declare namespace Request {
    export type Raw = PauseSchedule.Raw | null | undefined;
}
