// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const BrowserProfileCreate: core.serialization.Schema<
    serializers.BrowserProfileCreate.Raw,
    Omit<HaiAgents.BrowserProfileCreate, "profileId">
> = core.serialization.object({
    name: core.serialization.string(),
    browserName: core.serialization.property("browser_name", core.serialization.string()),
    browserVersion: core.serialization.property("browser_version", core.serialization.string()),
    description: core.serialization.string().optionalNullable(),
    labels: core.serialization.record(core.serialization.string(), core.serialization.string()).optional(),
});

export declare namespace BrowserProfileCreate {
    export interface Raw {
        name: string;
        browser_name: string;
        browser_version: string;
        description?: (string | null | undefined) | null;
        labels?: Record<string, string> | null;
    }
}
