// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Browser } from "../../../types/Browser.js";
import { Desktop } from "../../../types/Desktop.js";

export const CreateEnvironmentRequest: core.serialization.Schema<
    serializers.CreateEnvironmentRequest.Raw,
    HaiAgents.CreateEnvironmentRequest
> = core.serialization
    .union("kind", {
        web: Browser,
        desktop: Desktop,
    })
    .transform<HaiAgents.CreateEnvironmentRequest>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace CreateEnvironmentRequest {
    export type Raw = CreateEnvironmentRequest.Web | CreateEnvironmentRequest.Desktop;

    export interface Web extends Browser.Raw {
        kind: "web";
    }

    export interface Desktop extends Desktop.Raw {
        kind: "desktop";
    }
}
