// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const ListEnvironmentsRequestSortItem: core.serialization.Schema<
    serializers.ListEnvironmentsRequestSortItem.Raw,
    HaiAgents.ListEnvironmentsRequestSortItem
> = core.serialization.enum_(["created_at", "-created_at", "id", "-id"]);

export declare namespace ListEnvironmentsRequestSortItem {
    export type Raw = "created_at" | "-created_at" | "id" | "-id";
}
