// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { BrowserTextMode } from "../../../types/BrowserTextMode.js";
import { BrowserVisualMode } from "../../../types/BrowserVisualMode.js";

export const PatchEnvironmentMode: core.serialization.Schema<
    serializers.PatchEnvironmentMode.Raw,
    HaiAgents.PatchEnvironmentMode
> = core.serialization.undiscriminatedUnion([BrowserVisualMode, BrowserTextMode]);

export declare namespace PatchEnvironmentMode {
    export type Raw = BrowserVisualMode.Raw | BrowserTextMode.Raw;
}
