// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Browser } from "../../../types/Browser.js";

export const UpdateEnvironmentRequestBody: core.serialization.Schema<
    serializers.UpdateEnvironmentRequestBody.Raw,
    HaiAgents.UpdateEnvironmentRequestBody
> = core.serialization
    .union("kind", {
        web: Browser,
    })
    .transform<HaiAgents.UpdateEnvironmentRequestBody>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace UpdateEnvironmentRequestBody {
    export type Raw = UpdateEnvironmentRequestBody.Web;

    export interface Web extends Browser.Raw {
        kind: "web";
    }
}
