// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Android } from "../../../types/Android.js";
import { Browser } from "../../../types/Browser.js";
import { Desktop } from "../../../types/Desktop.js";
import { Workstation } from "../../../types/Workstation.js";

export const UpdateEnvironmentRequestBody: core.serialization.Schema<
    serializers.UpdateEnvironmentRequestBody.Raw,
    HaiAgents.UpdateEnvironmentRequestBody
> = core.serialization
    .union("kind", {
        web: Browser,
        desktop: Desktop,
        android: Android,
        workstation: Workstation,
    })
    .transform<HaiAgents.UpdateEnvironmentRequestBody>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace UpdateEnvironmentRequestBody {
    export type Raw =
        | UpdateEnvironmentRequestBody.Web
        | UpdateEnvironmentRequestBody.Desktop
        | UpdateEnvironmentRequestBody.Android
        | UpdateEnvironmentRequestBody.Workstation;

    export interface Web extends Browser.Raw {
        kind: "web";
    }

    export interface Desktop extends Desktop.Raw {
        kind: "desktop";
    }

    export interface Android extends Android.Raw {
        kind: "android";
    }

    export interface Workstation extends Workstation.Raw {
        kind: "workstation";
    }
}
