// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListSkillsRequest {
    /** Case-insensitive substring match on skill name. */
    name?: string | null;
    /** Case-insensitive match on skill name or description. */
    search?: string | null;
    /** Page number (1-based) */
    page?: number;
    /** Number of items per page */
    size?: number;
    /** Sort by field */
    sort?: HaiAgents.ListSkillsRequestSortItem[] | null;
}
