// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface PatchSkill {
    name: string;
    description?: string | null;
    body?: string | null;
    source?: string | null;
    urlPattern?: string | null;
}
