// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "name",
 *         body: {
 *             name: "name",
 *             description: "description",
 *             body: "body"
 *         }
 *     }
 */
export interface UpdateSkillRequest {
    name: string;
    body: HaiAgents.Skill;
}
