// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const VaultTokenRotateRequest: core.serialization.Schema<
    serializers.VaultTokenRotateRequest.Raw,
    Omit<HaiAgents.VaultTokenRotateRequest, "vaultId">
> = core.serialization.object({
    token: core.serialization.string(),
});

export declare namespace VaultTokenRotateRequest {
    export interface Raw {
        token: string;
    }
}
