// This file was auto-generated by Fern from our API Definition.

export const ListSchedulesRequestSortItem = {
    CreatedAtAsc: "created_at",
    CreatedAtDesc: "-created_at",
} as const;
export type ListSchedulesRequestSortItem =
    (typeof ListSchedulesRequestSortItem)[keyof typeof ListSchedulesRequestSortItem];
