// This file was auto-generated by Fern from our API Definition.

export const ListScheduleRunsRequestSortItem = {
    ScheduledForAsc: "scheduled_for",
    ScheduledForDesc: "-scheduled_for",
} as const;
export type ListScheduleRunsRequestSortItem =
    (typeof ListScheduleRunsRequestSortItem)[keyof typeof ListScheduleRunsRequestSortItem];
