// This file was auto-generated by Fern from our API Definition.

export const ActiveStateChangeDataState = {
    Running: "running",
    Idle: "idle",
    AwaitingToolResults: "awaiting_tool_results",
} as const;
export type ActiveStateChangeDataState = (typeof ActiveStateChangeDataState)[keyof typeof ActiveStateChangeDataState];
