// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

export interface ActiveStateChangeData {
    state: HaiAgents.ActiveStateChangeDataState;
    pendingToolCalls?: HaiAgents.ToolRequest[] | null;
    /** Accepts any additional properties */
    [key: string]: any;
}
