// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * The agent switched between running, idle and awaiting custom tool results.
 */
export interface ActiveStateChangeEvent {
    timestamp: Date;
    data: HaiAgents.ActiveStateChangeData;
    /** Accepts any additional properties */
    [key: string]: any;
}
