// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * Declarative agent definition.
 */
export interface Agent {
    /** Unique name for this agent in your catalog. Format: lowercase ASCII letters, digits and hyphens; must start and end with alphanumeric; max 63 chars per segment; optional single 'org/' namespace prefix (e.g. 'h/web-environment'). */
    name: string;
    /** What the agent does. Parent agents read this to decide when to delegate to it. */
    description: string;
    /** Environments the agent runs in. Each entry is a registered environment's id or an inline definition. At most one per kind. Required unless the agent delegates to subagents (a pure orchestrator owns none). */
    environments: HaiAgents.AgentEnvironmentsItem[];
    /** Model that serves the agent. Defaults to the platform model if omitted. */
    model?: string | null;
    /** Instructions appended to the agent's system prompt to steer behavior. */
    instructions?: string | null;
    /** Agents this one can delegate to. Each entry is a registered agent's name or an inline definition. */
    subagents?: HaiAgents.AgentSubagentsItem[] | null;
    /** Skills the agent can draw on. Each entry is a registered skill's name or an inline definition. */
    skills?: HaiAgents.AgentSkillsItem[] | null;
    /** JSON Schema the agent's final answer must conform to. Null returns a free-form text answer. */
    answerFormat?: Record<string, unknown> | null;
}
