// This file was auto-generated by Fern from our API Definition.

export interface AgentErrorData {
    error: string;
    trace?: string;
    info?: Record<string, unknown> | null;
    /** Accepts any additional properties */
    [key: string]: any;
}
