// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

export type AgentEnvironmentsItemOne = HaiAgents.AgentEnvironmentsItemOne.Web;

export namespace AgentEnvironmentsItemOne {
    export interface Web extends HaiAgents.Browser {
        kind: "web";
    }
}
