// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

export type AgentEventData =
    | HaiAgents.AgentEventData.AnswerEvent
    | HaiAgents.AgentEventData.ErrorEvent
    | HaiAgents.AgentEventData.FlowEvent
    | HaiAgents.AgentEventData.MessageEvent
    | HaiAgents.AgentEventData.ObservationEvent
    | HaiAgents.AgentEventData.PolicyEvent
    | HaiAgents.AgentEventData.ToolResult;

export namespace AgentEventData {
    export interface AnswerEvent extends HaiAgents.AnswerEvent {
        kind: "answer_event";
    }

    export interface ErrorEvent extends HaiAgents.ErrorEvent {
        kind: "error_event";
    }

    export interface FlowEvent extends HaiAgents.FlowEvent {
        kind: "flow_event";
    }

    export interface MessageEvent extends HaiAgents.MessageEvent {
        kind: "message_event";
    }

    export interface ObservationEvent extends HaiAgents.ObservationEvent {
        kind: "observation_event";
    }

    export interface PolicyEvent extends HaiAgents.PolicyEvent {
        kind: "policy_event";
    }

    export interface ToolResult extends HaiAgents.ToolResultEvent {
        kind: "tool_result";
    }
}
