// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * The agent run completed.
 */
export interface AgentCompletionEvent {
    timestamp: Date;
    data: HaiAgents.AgentCompletionData;
    /** Accepts any additional properties */
    [key: string]: any;
}
