// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

export interface AgentCompletionData {
    reason: HaiAgents.AgentCompletionDataReason;
    /** Accepts any additional properties */
    [key: string]: any;
}
