// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * The agent process started.
 */
export interface AgentStartedEvent {
    timestamp: Date;
    data: HaiAgents.AgentStartedData;
    /** Accepts any additional properties */
    [key: string]: any;
}
