// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * Event emitted by the agent loop itself; ``data`` is discriminated by ``kind``.
 */
export interface AgentEvent {
    timestamp: Date;
    data: HaiAgents.AgentEventData;
    /** Accepts any additional properties */
    [key: string]: any;
}
