// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * The run status changed.
 */
export interface AgentRunStatusChangeEvent {
    timestamp: Date;
    data: HaiAgents.AgentRunStatusChangeData;
    /** Accepts any additional properties */
    [key: string]: any;
}
