// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

export interface AgentRunStatusChangeData {
    status: HaiAgents.AgentRunStatusChangeDataStatus;
    /** Accepts any additional properties */
    [key: string]: any;
}
