// This file was auto-generated by Fern from our API Definition.

export const AgentReasoningEffort = {
    Disabled: "disabled",
    Low: "low",
    Medium: "medium",
    Xhigh: "xhigh",
} as const;
export type AgentReasoningEffort = (typeof AgentReasoningEffort)[keyof typeof AgentReasoningEffort];
