// This file was auto-generated by Fern from our API Definition.

/** Agent's self-assessment of how the task concluded, reported with the final answer. */
export const AnswerOutcome = {
    Success: "success",
    Partial: "partial",
    Infeasible: "infeasible",
    Blocked: "blocked",
} as const;
export type AnswerOutcome = (typeof AnswerOutcome)[keyof typeof AnswerOutcome];
