// This file was auto-generated by Fern from our API Definition.

/**
 * Final answer, plain text or structured JSON; any embedded image is inlined as base64, not a URL.
 */
export type AnswerEventAnswer = string | Record<string, unknown>;
