// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * A file passed between the user and the agent's environment; ``data.url`` downloads it.
 */
export interface AttachmentEvent {
    timestamp: Date;
    data: HaiAgents.AttachmentData;
    /** Accepts any additional properties */
    [key: string]: any;
}
