// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

export interface AttachmentData {
    origin: HaiAgents.AttachmentDataOrigin;
    name: string;
    path: string;
    mediaType: string;
    sizeBytes: number;
    url: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
