// This file was auto-generated by Fern from our API Definition.

export const AttachmentDataOrigin = {
    Agent: "agent",
    User: "user",
} as const;
export type AttachmentDataOrigin = (typeof AttachmentDataOrigin)[keyof typeof AttachmentDataOrigin];
