// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * How the agent perceives and drives the browser.
 */
export type BrowserMode = HaiAgents.BrowserMode.Text | HaiAgents.BrowserMode.Visual;

export namespace BrowserMode {
    export interface Text extends HaiAgents.BrowserTextMode {
        type: "text";
    }

    export interface Visual extends HaiAgents.BrowserVisualMode {
        type: "visual";
    }
}
