// This file was auto-generated by Fern from our API Definition.

export const BrowserVisualModeType = {
    Visual: "visual",
} as const;
export type BrowserVisualModeType = (typeof BrowserVisualModeType)[keyof typeof BrowserVisualModeType];
