// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * A web browser the agent navigates and acts on.
 */
export interface Browser {
    /** Catalog identifier for this environment. */
    id: string;
    kind?: HaiAgents.BrowserKind;
    /** Run without a visible window. */
    headless: boolean;
    /** Viewport width in pixels. */
    width: number;
    /** Viewport height in pixels. */
    height: number;
    /** Initial URL to open. Null starts on a blank page. */
    startUrl: string | null;
    /** How the agent perceives and drives the browser. 'visual': act on screenshots by viewport coordinates. 'multimodal': the same, with the page also included as markdown text alongside each screenshot. 'text': read-only markdown with URL navigation, no screenshots. */
    mode?: HaiAgents.BrowserMode;
}
