// This file was auto-generated by Fern from our API Definition.

/**
 * Response model for a browser profile.
 */
export interface BrowserProfileRead {
    id: string;
    userId: string;
    orgId: string;
    name: string;
    description?: string | null;
    browserName: string;
    browserVersion: string;
    s3Path?: string | null;
    fileSizeBytes?: number | null;
    checksum?: string | null;
    usageCount?: number;
    lastUsedAt?: Date | null;
    labels?: Record<string, unknown> | null;
    createdAt: Date;
    updatedAt: Date;
}
