// This file was auto-generated by Fern from our API Definition.

/** Where the browser runs: 'cloud' on H Company infrastructure, or 'user_device' on your own machine. */
export const BrowserHost = {
    UserDevice: "user_device",
    Cloud: "cloud",
} as const;
export type BrowserHost = (typeof BrowserHost)[keyof typeof BrowserHost];
