// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * A web browser the agent navigates and acts on.
 */
export interface Browser {
    /** Catalog identifier for this environment. */
    id: string;
    kind?: HaiAgents.BrowserKind;
    /** Run without a visible window. */
    headless?: boolean;
    /** Viewport width in pixels. */
    width?: number;
    /** Viewport height in pixels. */
    height?: number;
    /** Initial URL to open. */
    startUrl?: string;
    /** How the agent perceives and drives the browser. 'visual': act on screenshots by viewport coordinates. 'multimodal': the same, with the page also included as markdown text alongside each screenshot. 'text': read-only markdown with URL navigation, no screenshots. */
    mode?: HaiAgents.BrowserMode;
    /** Characters of page text shown per page in 'text' mode. */
    pageChars?: number;
    /** Id of a vault config to bind to this browser, letting the agent sign in to sites with secrets resolved from the vault. The vault must belong to the caller's organization. Omit to run without secret access. */
    vaultId?: string | null;
    /** Id of a browser profile to load into this browser, restoring saved cookies and storage state from a prior session. The profile must belong to the caller's organization. Omit to run with a fresh profile. */
    browserProfileId?: string | null;
    /** Optional network configuration for the remote browser session. Applied only when a new runner session is provisioned (not when session_id is set). */
    network?: HaiAgents.BrowserNetwork | null;
}
