// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * A web browser the agent navigates and acts on.
 */
export interface Browser {
    /** Catalog identifier for this environment. */
    id: string;
    kind?: HaiAgents.BrowserKind;
    /** Initial URL to open. */
    startUrl?: string;
    /** Run the browser without a visible window. */
    headless?: boolean;
    /** How the agent perceives and drives the browser. */
    mode?: HaiAgents.BrowserMode;
    /** Id of a vault config to bind to this browser, letting the agent sign in to sites with secrets resolved from the vault. The vault must belong to the caller's organization. Omit to run without secret access. */
    vaultId?: string | null;
    /** Id of a browser profile to load into this browser, restoring saved cookies and storage state from a prior session. The profile must belong to the caller's organization. Omit to run with a fresh profile. */
    browserProfileId?: string | null;
    /** Optional network configuration for the remote browser session. Applied only when a new runner session is provisioned (not when session_id is set). */
    network?: HaiAgents.BrowserNetwork | null;
}
