// This file was auto-generated by Fern from our API Definition.

export const BrowserTextModeType = {
    Text: "text",
} as const;
export type BrowserTextModeType = (typeof BrowserTextModeType)[keyof typeof BrowserTextModeType];
