// This file was auto-generated by Fern from our API Definition.

/**
 * Read-only markdown with URL navigation, no screenshots.
 */
export interface BrowserTextMode {
    /** Characters of page text shown per page. */
    chunkSize?: number;
}
