// This file was auto-generated by Fern from our API Definition.

/** How the agent perceives and drives the browser. 'visual': act on screenshots by viewport coordinates. 'multimodal': the same, with the page also included as markdown text alongside each screenshot. 'text': read-only markdown with URL navigation, no screenshots. */
export const BrowserMode = {
    Visual: "visual",
    Text: "text",
    Multimodal: "multimodal",
} as const;
export type BrowserMode = (typeof BrowserMode)[keyof typeof BrowserMode];
