// This file was auto-generated by Fern from our API Definition.

/**
 * Network egress settings for a remote browser session.
 */
export interface BrowserNetwork {
    /** Optional bring-your-own HTTP/HTTPS/SOCKS proxy URL for browser egress (e.g. http://user:pass@proxy.example.com:8080). Applied when provisioning a new remote browser session. Only supported for headful chromium-based runners. Ignored when session_id attaches to an existing session. */
    proxyUrl?: string | null;
}
