// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * Cron cadence evaluated in an IANA timezone.
 */
export interface CronTiming {
    type?: HaiAgents.CronTimingType;
    /** Five-field cron expression, e.g. '0 9 * * 1-5'. */
    expression: string;
    /** IANA timezone the expression is evaluated in, e.g. 'Europe/Paris'. */
    timezone: string;
}
