// This file was auto-generated by Fern from our API Definition.

/** Where the desktop runs: 'cloud' on H Company infrastructure, or 'user_device' on your own machine. */
export const DesktopHost = {
    UserDevice: "user_device",
    Cloud: "cloud",
} as const;
export type DesktopHost = (typeof DesktopHost)[keyof typeof DesktopHost];
