// This file was auto-generated by Fern from our API Definition.

export const DesktopHost = {
    UserDevice: "user_device",
} as const;
export type DesktopHost = (typeof DesktopHost)[keyof typeof DesktopHost];
