// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * A desktop the agent controls via mouse, keyboard, and screenshots.
 */
export interface Desktop {
    /** Catalog identifier for this environment. */
    id: string;
    host: HaiAgents.DesktopHost;
    /** Connect to an existing desktop session by id instead of starting a new one. */
    sessionId?: string | null;
}
