// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

export type Environment = HaiAgents.Environment.Desktop | HaiAgents.Environment.Web;

export namespace Environment {
    export interface Desktop extends HaiAgents.Desktop {
        kind: "desktop";
    }

    export interface Web extends HaiAgents.Browser {
        kind: "web";
    }
}
