// This file was auto-generated by Fern from our API Definition.

/** Environment family. */
export const EnvironmentKind = {
    Web: "web",
} as const;
export type EnvironmentKind = (typeof EnvironmentKind)[keyof typeof EnvironmentKind];
