// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * Named page subclass so OpenAPI emits a clean ``EnvironmentPage`` schema name.
 */
export interface EnvironmentPage {
    items: HaiAgents.Environment[];
    total: number;
    page: number;
}
