// This file was auto-generated by Fern from our API Definition.

export const ErrorEventKind = {
    ErrorEvent: "error_event",
} as const;
export type ErrorEventKind = (typeof ErrorEventKind)[keyof typeof ErrorEventKind];
