// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * Recoverable error raised while running the agent loop.
 */
export interface ErrorEvent {
    kind?: HaiAgents.ErrorEventKind;
    error: string;
    /** Component that raised the error. */
    origin: string;
    /** Tool request being executed, if any. */
    toolReq?: HaiAgents.ToolRequest | null;
}
