// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

export interface FileTransferData {
    direction: HaiAgents.FileTransferDataDirection;
    path: string;
    sizeBytes?: number | null;
    /** Accepts any additional properties */
    [key: string]: any;
}
