// This file was auto-generated by Fern from our API Definition.

/**
 * One entry in a directory listing.
 */
export interface FileEntry {
    name: string;
    path: string;
    sizeBytes: number;
    modifiedAt: Date;
    isDir: boolean;
}
