// This file was auto-generated by Fern from our API Definition.

export const FileTransferDataDirection = {
    Download: "download",
    Upload: "upload",
} as const;
export type FileTransferDataDirection = (typeof FileTransferDataDirection)[keyof typeof FileTransferDataDirection];
