// This file was auto-generated by Fern from our API Definition.

/**
 * Run-loop control transition (pause, resume, stop, ...).
 */
export interface FlowEvent {
    /** Control signal, e.g. "pause", "resume", "force_answer". */
    flow: string;
    /** Who triggered the transition. */
    origin: string;
}
