// This file was auto-generated by Fern from our API Definition.

export const ImageContentType = {
    Url: "url",
    Base64: "base64",
} as const;
export type ImageContentType = (typeof ImageContentType)[keyof typeof ImageContentType];
