// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * Image payload: ``url`` for platform-served screenshots, ``base64`` for inline images.
 */
export interface ImageContent {
    /** Image location: a fetchable URL or a base64 payload, per ``type``. */
    source: string;
    type: HaiAgents.ImageContentType;
    /** MIME type, e.g. "image/png". */
    mediaType?: string | null;
}
