// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * Directory listing, newest first; ``truncated`` when capped at ``max_entries``.
 */
export interface ListFilesResponse {
    path: string;
    files: HaiAgents.FileEntry[];
    truncated: boolean;
}
