// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * A live view URL became available.
 */
export interface LiveViewUrlEvent {
    timestamp: Date;
    data: HaiAgents.LiveViewUrlData;
    /** Accepts any additional properties */
    [key: string]: any;
}
