// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * Request for an H-managed proxy, provisioned per session.
 *
 * Describes intent only — pool, country, stickiness — never credentials; H resolves
 * and injects those when provisioning the session, including which provider backs
 * the requested pool.
 */
export interface ManagedProxySelection {
    /** Two-letter ISO 3166-1 country to source IPs from (e.g. 'US'). Validated server-side. */
    country?: string | null;
    /** Keep the same IP across the session where the pool allows it. */
    sticky?: boolean;
    /** Which upstream IP pool to draw from. */
    pool?: HaiAgents.ProxyPool;
}
