// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * An MCP server an environment connects to.
 */
export interface McpServer {
    /** Unique name for this server. */
    name: string;
    /** Transport used to reach the server. */
    transport: HaiAgents.McpServerTransport;
    /** Executable to launch, for the stdio transport. */
    command?: string | null;
    /** Command-line arguments, for the stdio transport. */
    args?: string[];
    /** Subprocess environment variables, for the stdio transport. */
    env?: Record<string, string>;
    /** Server endpoint URL, for the HTTP transports. */
    url?: string | null;
    /** Request headers, for the HTTP transports. */
    headers?: Record<string, string>;
}
