// This file was auto-generated by Fern from our API Definition.

/** Transport used to reach the server. */
export const McpServerTransport = {
    Stdio: "stdio",
    StreamableHttp: "streamable_http",
    Sse: "sse",
} as const;
export type McpServerTransport = (typeof McpServerTransport)[keyof typeof McpServerTransport];
