// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * Message exchanged with the agent (user, system or subagent).
 */
export interface MessageEvent {
    callerId: string;
    content?: HaiAgents.MessageEventContentItem[];
}
