// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * Rolled-up usage and cost for a session.
 */
export interface Metrics {
    /** Steps taken so far. */
    steps?: number | undefined;
    /** Per-model token usage and cost. */
    cost_per_model?: HaiAgents.ModelCost[] | undefined;
    /** Total input cost in USD; null if any model is unpriced. */
    input_cost?: (number | null) | undefined;
    /** Total output cost in USD; null if any model is unpriced. */
    output_cost?: (number | null) | undefined;
    /** Total reasoning cost in USD; null if any model is unpriced. */
    reasoning_cost?: (number | null) | undefined;
    /** Total cost in USD; null if any model is unpriced. */
    total_cost?: (number | null) | undefined;
}
