// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * Rolled-up usage and cost for a session.
 */
export interface Metrics {
    /** Steps taken so far. */
    steps?: number;
    /** Per-model token usage and cost. */
    costPerModel?: HaiAgents.ModelCost[];
    /** Total input cost in USD; null if any model is unpriced. */
    inputCost?: number | null;
    /** Total output cost in USD; null if any model is unpriced. */
    outputCost?: number | null;
    /** Total reasoning cost in USD; null if any model is unpriced. */
    reasoningCost?: number | null;
    /** Total cost in USD; null if any model is unpriced. */
    totalCost?: number | null;
    /** Accepts any additional properties */
    [key: string]: any;
}
