// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * Rolled-up usage and cost metrics for the session.
 */
export interface MetricsUpdateEvent {
    timestamp: Date;
    data: HaiAgents.MetricsUpdateData;
    /** Accepts any additional properties */
    [key: string]: any;
}
