// This file was auto-generated by Fern from our API Definition.

/**
 * Per-model token usage.
 */
export interface ModelUsage {
    /** Model id. */
    name: string;
    /** Input tokens consumed. */
    inputTokens: number;
    /** Output tokens produced. */
    outputTokens: number;
    /** Reasoning tokens produced. */
    reasoningTokens: number;
}
