// This file was auto-generated by Fern from our API Definition.

/**
 * Token usage and cost for a single model.
 */
export interface ModelCost {
    /** Model id. */
    name: string;
    /** Input tokens consumed. */
    inputTokens: number;
    /** Output tokens produced. */
    outputTokens: number;
    /** Reasoning tokens produced. */
    reasoningTokens: number;
    /** Input cost in USD; null if the model is unpriced. */
    inputCost?: number | null;
    /** Output cost in USD; null if the model is unpriced. */
    outputCost?: number | null;
    /** Reasoning cost in USD; null if the model is unpriced. */
    reasoningCost?: number | null;
    /** Total cost in USD; null if the model is unpriced. */
    totalCost?: number | null;
    /** Accepts any additional properties */
    [key: string]: any;
}
