// This file was auto-generated by Fern from our API Definition.

/**
 * Per-model token usage.
 */
export interface ModelUsage {
    /** Model id. */
    name: string;
    /** Input tokens consumed. */
    input_tokens: number;
    /** Output tokens produced. */
    output_tokens: number;
    /** Reasoning tokens produced. */
    reasoning_tokens: number;
}
