// This file was auto-generated by Fern from our API Definition.

/**
 * Token usage and cost for a single model.
 */
export interface ModelCost {
    /** Model id. */
    name: string;
    /** Input tokens consumed. */
    input_tokens: number;
    /** Output tokens produced. */
    output_tokens: number;
    /** Reasoning tokens produced. */
    reasoning_tokens: number;
    /** Input cost in USD; null if the model is unpriced. */
    input_cost?: (number | null) | undefined;
    /** Output cost in USD; null if the model is unpriced. */
    output_cost?: (number | null) | undefined;
    /** Reasoning cost in USD; null if the model is unpriced. */
    reasoning_cost?: (number | null) | undefined;
    /** Total cost in USD; null if the model is unpriced. */
    total_cost?: (number | null) | undefined;
}
