// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * What the agent perceived this step: optional text, screenshot and environment metadata.
 */
export interface ObservationEvent {
    /** Environment that produced the observation, e.g. "web". */
    type?: string | null;
    text?: string | null;
    image?: HaiAgents.ImageContent | null;
    /** Environment-specific snapshot, shaped by ``type``. */
    metadata?: Record<string, unknown>;
}
