// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * 1Password vault provider config.
 */
export interface OnePasswordConfig {
    provider?: HaiAgents.OnePasswordConfigProvider;
    opVaultId: string;
}
