// This file was auto-generated by Fern from our API Definition.

export const OnePasswordConfigProvider = {
    Onepassword: "onepassword",
} as const;
export type OnePasswordConfigProvider = (typeof OnePasswordConfigProvider)[keyof typeof OnePasswordConfigProvider];
