// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

export interface PageWebhookRecord {
    items: HaiAgents.WebhookRecord[];
    total: number;
    page: number;
}
