// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

export interface PageSkill {
    items: HaiAgents.Skill[];
    total: number;
    page: number;
}
