// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

export interface PageSessionSummary {
    items: HaiAgents.SessionSummary[];
    total: number;
    page: number;
}
