// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

export interface PageTrajectoryEvent {
    items: HaiAgents.TrajectoryEvent[];
    total: number;
    page: number;
}
