// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

export interface PageScheduleRunRecord {
    items: HaiAgents.ScheduleRunRecord[];
    total: number;
    page: number;
}
