// This file was auto-generated by Fern from our API Definition.

/** The kind of upstream IPs a managed proxy draws from. */
export const ProxyPool = {
    Residential: "residential",
    Datacenter: "datacenter",
    Isp: "isp",
    Mobile: "mobile",
} as const;
export type ProxyPool = (typeof ProxyPool)[keyof typeof ProxyPool];
