// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * Quota status.
 */
export interface QuotaStatus {
    scope: HaiAgents.QuotaStatusScope;
    limit: number;
    active: number;
    available: number;
}
