// This file was auto-generated by Fern from our API Definition.

export const QuotaStatusScope = {
    User: "user",
    Org: "org",
} as const;
export type QuotaStatusScope = (typeof QuotaStatusScope)[keyof typeof QuotaStatusScope];
