// This file was auto-generated by Fern from our API Definition.

/**
 * A file's base64 contents and metadata.
 */
export interface ReadFileResponse {
    path: string;
    contentBase64: string;
    sizeBytes: number;
    modifiedAt: Date;
}
