// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * The start request was dispatched to a runner.
 */
export interface RequestStartDispatchedEvent {
    timestamp: Date;
    data: HaiAgents.RequestStartDispatchedData;
    /** Accepts any additional properties */
    [key: string]: any;
}
