// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * The platform requested the agent to start.
 */
export interface RequestStartEvent {
    timestamp: Date;
    data: HaiAgents.RequestStartData;
    /** Accepts any additional properties */
    [key: string]: any;
}
