// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * A session-manager session hosting one of this session's environments became addressable by id.
 */
export interface RunnerSessionEvent {
    timestamp: Date;
    data: HaiAgents.RunnerSessionData;
    /** Accepts any additional properties */
    [key: string]: any;
}
