// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * Schedule as returned by reads.
 */
export interface ScheduleRecord {
    id: string;
    name: string;
    description: string | null;
    timing: HaiAgents.CronTiming;
    sessionRequest: HaiAgents.SessionRequest;
    paused: boolean;
    pauseNote: string | null;
    /** The next few fire times, empty while paused. */
    nextRunTimes: Date[];
    lastRunAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
}
