// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * Outcome of one schedule fire.
 */
export interface ScheduleRunRecord {
    id: string;
    scheduleId: string;
    status: HaiAgents.ScheduleRunRecordStatus;
    scheduledFor: Date;
    sessionId: string | null;
    error: string | null;
    triggeredManually: boolean;
    createdAt: Date;
}
