// This file was auto-generated by Fern from our API Definition.

/** Machine-readable category of a terminal session failure. */
export const SessionErrorCode = {
    EnvironmentError: "environment_error",
    NoAnswer: "no_answer",
    AnswerValidation: "answer_validation",
    Timeout: "timeout",
    Internal: "internal",
} as const;
export type SessionErrorCode = (typeof SessionErrorCode)[keyof typeof SessionErrorCode];
