// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * Full session envelope: original request + live status.
 */
export interface Session {
    id: string;
    request: HaiAgents.SessionRequest;
    status: HaiAgents.SessionStatus;
    /** The agent's most recent final answer: free-form text, or structured data when the agent runs with a custom answer format. Null until the agent first answers. Mirrors the answer streamed from the changes endpoint, surfaced here for non-interactive runs. */
    latest_answer?: unknown | undefined;
    created_at: string;
    started_at?: (string | null) | undefined;
    finished_at?: (string | null) | undefined;
}
