// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * Flat projection for session listings, including child rosters via ``?parent_session_id=``.
 */
export interface SessionSummary {
    id: string;
    agent?: string | null;
    status: HaiAgents.TrajectoryStatus;
    /** URL of the session's Agent View page on the H Platform (live view and replay). */
    agentViewUrl?: string | null;
    firstMessage?: HaiAgents.UserMessageEvent | null;
    createdAt: Date;
    startedAt?: Date | null;
    finishedAt?: Date | null;
    /** When the session's latest event was ingested (agent steps, status changes, user messages). Null for sessions that predate this field. */
    lastActivityAt?: Date | null;
    /** When the session's PII text and screenshots were irreversibly anonymized. Null if not anonymized. */
    anonymizedAt?: Date | null;
}
