// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * ``POST /api/v2/sessions`` body.
 */
export interface SessionRequest {
    /** Agent to run: a registered agent's name, or an inline Agent definition. */
    agent: HaiAgents.SessionRequestAgent;
    /** Initial task for the agent. A plain string, a single message, or a list of messages. */
    messages?: HaiAgents.SessionRequestMessages | null;
    /** Maximum reasoning steps the agent may take. Unbounded if null. */
    maxSteps?: number | null;
    /** Maximum wall-clock seconds the agent may run. Unbounded if null. */
    maxTimeS?: number | null;
    /** Seconds to keep the session open for follow-up messages after each answer. Null ends the session as soon as the agent answers. */
    idleTimeoutS?: number | null;
    /** Optional id to group and list related sessions together. */
    groupId?: string | null;
    /** Id of the parent session, when this is a child run. */
    parentSessionId?: string | null;
    /** Target version of the agent artifact to use. */
    agentArtifact?: string | null;
    /** Per-run overrides applied to the resolved request, keyed by a dotted path. List members are selected with an explicit [field=value] clause, e.g. {"agent.environments[kind=web].start_url": "https://bing.com"}. Each value must match the type of the field its path targets. */
    overrides?: Record<string, unknown>;
}
