// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * Initial task for the agent. A plain string, a single message, or a list of messages.
 */
export type SessionRequestMessages = string | HaiAgents.UserMessageEvent | HaiAgents.UserMessageEvent[];
