// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * Typed view of ``TrajectoryChanges`` for Agent API session endpoints.
 */
export interface SessionChanges {
    status: HaiAgents.TrajectoryStatus;
    startedAt?: Date | null;
    finishedAt?: Date | null;
    error?: string | null;
    errorCode?: HaiAgents.SessionErrorCode | null;
    newEvents?: HaiAgents.SessionEvent[];
    answer?: HaiAgents.SessionChangesAnswer | null;
    outcome?: HaiAgents.AnswerOutcome | null;
    metrics?: HaiAgents.Metrics;
}
