// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * Agent to run: a registered agent's name, or an inline Agent definition.
 */
export type SessionRequestAgent = string | HaiAgents.Agent;
