// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * ``GET /api/v2/sessions/{id}/status`` response.
 */
export interface SessionStatus {
    /** Current lifecycle state of the session. */
    status: HaiAgents.TrajectoryStatus;
    /** Error message if the session failed; null otherwise. */
    error?: (string | null) | undefined;
    /** Number of steps the agent has taken. */
    steps?: number | undefined;
    /** Per-model token usage. Empty until the agent calls a model. */
    usage_per_model?: HaiAgents.ModelUsage[] | undefined;
    /** Session ids of any subagents this session spawned. */
    subagent_session_ids?: string[] | undefined;
}
