// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * Flat projection for session listings, including child rosters via ``?parent_session_id=``.
 */
export interface SessionSummary {
    id: string;
    agent?: string | null;
    status: HaiAgents.TrajectoryStatus;
    firstMessage?: HaiAgents.UserMessageEvent | null;
    createdAt: Date;
    startedAt?: Date | null;
    finishedAt?: Date | null;
}
