// This file was auto-generated by Fern from our API Definition.

/**
 * Public share URL for a session.
 *
 * ``share_url`` is a path; clients prepend the AgP host. Today this points at the
 * v1 share router (``/share/api/v1/trajectories/{id}``); will migrate to
 * ``/share/v1/sessions/{id}`` once the v2 share router lands.
 */
export interface ShareLink {
    share_url: string;
}
