// This file was auto-generated by Fern from our API Definition.

/**
 * A named, reusable instruction an agent can draw on during a session.
 */
export interface Skill {
    /** Unique name for this skill in your catalog. Format: lowercase ASCII letters, digits and hyphens; must start and end with alphanumeric; max 63 chars per segment; optional single 'org/' namespace prefix (e.g. 'h/web-environment'). */
    name: string;
    /** When to use this skill. The agent reads this to decide whether to load it. */
    description: string;
    /** Markdown instructions the agent loads when it uses the skill. */
    body: string;
    /** Optional URL the content was sourced from. */
    source?: (string | null) | undefined;
    /** Optional regex hinting at URLs where this skill applies. */
    url_pattern?: (string | null) | undefined;
}
