// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * The client is sending back the result of a custom tool call.
 */
export interface ToolResultEvent {
    type?: HaiAgents.ToolResultEventType;
    /** Id of the pending tool call this result answers. */
    toolCallId: string;
    /** JSON-serializable tool output, shown to the model. */
    result?: unknown;
    /** Mark the call as failed; result is treated as the error text. */
    isError?: boolean;
}
