// This file was auto-generated by Fern from our API Definition.

export const ToolResultEventKind = {
    ToolResult: "tool_result",
} as const;
export type ToolResultEventKind = (typeof ToolResultEventKind)[keyof typeof ToolResultEventKind];
