// This file was auto-generated by Fern from our API Definition.

export const ToolResultBatchType = {
    Batch: "batch",
} as const;
export type ToolResultBatchType = (typeof ToolResultBatchType)[keyof typeof ToolResultBatchType];
