// This file was auto-generated by Fern from our API Definition.

/**
 * Contract for a tool executed by the API client, not by the agent runtime.
 *
 * The agent emits a tool call matching ``input_schema``, pauses, and resumes
 * once the client sends back the corresponding tool result.
 */
export interface ToolDefinition {
    /** Tool name advertised to the model. Format: letters, digits and underscores; must start with a letter or underscore; max 64 chars. */
    name: string;
    /** What the tool does, when to use it, and what it returns. Shown to the model verbatim. */
    description: string;
    /** JSON Schema (object type) describing the tool call arguments. */
    inputSchema?: Record<string, unknown>;
}
