// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

export type ToolResultBatchResultsItem =
    | HaiAgents.ToolResultBatchResultsItem.ErrorEvent
    | HaiAgents.ToolResultBatchResultsItem.ToolResult;

export namespace ToolResultBatchResultsItem {
    export interface ErrorEvent extends HaiAgents.ErrorEvent {
        kind: "error_event";
    }

    export interface ToolResult extends HaiAgents.ToolResultEvent {
        kind: "tool_result";
    }
}
