// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * Batch of custom tool results.
 */
export interface ToolResultBatch {
    type?: HaiAgents.ToolResultBatchType;
    results: HaiAgents.ToolResultBatchResultsItem[];
}
