// This file was auto-generated by Fern from our API Definition.

export const UserMessageEventType = {
    UserMessage: "user_message",
} as const;
export type UserMessageEventType = (typeof UserMessageEventType)[keyof typeof UserMessageEventType];
