// This file was auto-generated by Fern from our API Definition.

/**
 * The user is sending a message to an active agent.
 */
export interface UserMessageEvent {
    type?: UserMessageEvent.Type | undefined;
    /** Message text sent to the agent. */
    message: string;
    /** Optional images attached to the message, as base64 data URIs. */
    images?: string[] | undefined;
    caller_id?: string | undefined;
}

export namespace UserMessageEvent {
    export const Type = {
        UserMessage: "user_message",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
