// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * The user is sending a message to an active agent.
 */
export interface UserMessageEvent {
    type?: HaiAgents.UserMessageEventType;
    /** Message text sent to the agent. */
    message: string;
    /** Optional images attached to the message, as base64 data URIs. */
    images?: string[];
    /** Optional files attached to the message: up to 10, 7 MB in total. They are saved under /workspace/files on a workstation or code sandbox, and ~/Downloads on a cloud browser. */
    files?: HaiAgents.FileContent[];
    callerId?: string;
}
