// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * The user is sending a message to an active agent.
 */
export interface UserMessageEvent {
    type?: HaiAgents.UserMessageEventType;
    /** Message text sent to the agent. */
    message: string;
    /** Optional images attached to the message, as base64 data URIs. */
    images?: string[];
    callerId?: string;
}
