// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

export interface ValidationError {
    loc: HaiAgents.ValidationErrorLocItem[];
    msg: string;
    type: string;
    input?: unknown;
    ctx?: Record<string, unknown>;
}
