// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * Response model for a vault config. Never includes the stored token.
 */
export interface VaultConfigRead {
    id: string;
    orgId: string;
    name: string;
    providerConfig: HaiAgents.OnePasswordConfig;
    createdAt: Date;
    updatedAt: Date;
}
