// This file was auto-generated by Fern from our API Definition.

/**
 * Webhook as returned by reads; the signing secret is never included.
 */
export interface WebhookRecord {
    id: string;
    url: string;
    enabledEvents: string[];
    description: string | null;
    disabled: boolean;
    createdAt: Date;
    updatedAt: Date;
}
