// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * Create response: the only time the signing secret is returned.
 */
export interface WebhookWithSecret {
    id: string;
    url: string;
    enabledEvents: string[];
    description: string | null;
    disabled: boolean;
    /** Result of the most recent delivery attempt; null before the first attempt. */
    lastDeliveryStatus?: HaiAgents.WebhookWithSecretLastDeliveryStatus | null;
    /** What went wrong on the most recent delivery attempt; null when it succeeded. */
    lastDeliveryError?: string | null;
    /** When the most recent delivery attempt happened; null before the first attempt. */
    lastDeliveryAt?: Date | null;
    /** When a delivery last succeeded; null if none has. */
    lastSuccessAt?: Date | null;
    /** Failed delivery attempts since the last success. The endpoint is automatically disabled when this grows too large; resets to zero on success or re-enable. */
    consecutiveFailures?: number;
    createdAt: Date;
    updatedAt: Date;
    secret: string;
}
