// This file was auto-generated by Fern from our API Definition.

export const WebhookRecordLastDeliveryStatus = {
    Succeeded: "succeeded",
    Failed: "failed",
} as const;
export type WebhookRecordLastDeliveryStatus =
    (typeof WebhookRecordLastDeliveryStatus)[keyof typeof WebhookRecordLastDeliveryStatus];
