// This file was auto-generated by Fern from our API Definition.

/**
 * Create response: the only time the signing secret is returned.
 */
export interface WebhookWithSecret {
    id: string;
    url: string;
    enabledEvents: string[];
    description: string | null;
    disabled: boolean;
    createdAt: Date;
    updatedAt: Date;
    secret: string;
}
