// This file was auto-generated by Fern from our API Definition.

/**
 * A webhook event type clients can subscribe to.
 */
export interface WebhookEventTypeDefinition {
    type: string;
    description: string;
}
