// This file was auto-generated by Fern from our API Definition.

export const WebhookWithSecretLastDeliveryStatus = {
    Succeeded: "succeeded",
    Failed: "failed",
} as const;
export type WebhookWithSecretLastDeliveryStatus =
    (typeof WebhookWithSecretLastDeliveryStatus)[keyof typeof WebhookWithSecretLastDeliveryStatus];
