// This file was auto-generated by Fern from our API Definition.

/** Where the workstation runs: 'cloud' on H Company infrastructure, or 'user_device' on your own machine. */
export const WorkstationHost = {
    UserDevice: "user_device",
    Cloud: "cloud",
} as const;
export type WorkstationHost = (typeof WorkstationHost)[keyof typeof WorkstationHost];
