// This file was auto-generated by Fern from our API Definition.

/** Where the workstation runs: on H Company infrastructure. */
export const WorkstationHost = {
    Cloud: "cloud",
} as const;
export type WorkstationHost = (typeof WorkstationHost)[keyof typeof WorkstationHost];
