// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../index.js";

/**
 * A desktop computer with a browser, office apps and a shell, which the agent drives from that shell.
 */
export interface Workstation {
    /** Catalog identifier for this environment. */
    id: string;
    /** Where the workstation runs: on H Company infrastructure. */
    host?: HaiAgents.WorkstationHost;
}
