// This file was auto-generated by Fern from our API Definition.

/**
 * The written file's resolved path and byte count.
 */
export interface WriteFileResponse {
    path: string;
    sizeBytes: number;
}
