// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         agent_name: "agent_name"
 *     }
 */
export interface DeleteAgentRequest {
    agent_name: string;
}
