// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         agentName: "agent_name"
 *     }
 */
export interface GetAgentRequest {
    agentName: string;
    /** Materialise string environment/skill/subagent leaves into full specs. */
    resolve?: boolean;
}
