// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListAgentsRequest {
    /** Case-insensitive substring match on agent name. */
    agentName?: string | null;
    /** Case-insensitive match on agent name or description. */
    search?: string | null;
    /** Page number (1-based) */
    page?: number;
    /** Number of items per page */
    size?: number;
    /** Sort by field */
    sort?: HaiAgents.ListAgentsRequestSortItem[] | null;
}
