// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../index.js";

/**
 * @example
 *     {
 *         agentName: "agent_name"
 *     }
 */
export interface PatchAgent {
    agentName: string;
    description?: string | null;
    environments?: HaiAgents.PatchAgentEnvironmentsItem[] | null;
    model?: string | null;
    instructions?: string | null;
    subagents?: HaiAgents.PatchAgentSubagentsItem[] | null;
    skills?: HaiAgents.PatchAgentSkillsItem[] | null;
    answerFormat?: Record<string, unknown> | null;
    tools?: HaiAgents.ToolDefinition[] | null;
}
