// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../index.js";

/**
 * @example
 *     {
 *         agentName: "agent_name",
 *         body: {
 *             name: "name",
 *             description: "description",
 *             environments: ["environments"]
 *         }
 *     }
 */
export interface UpdateAgentRequest {
    agentName: string;
    body: HaiAgents.Agent;
}
