// This file was auto-generated by Fern from our API Definition.

export const ListWebhooksRequestSortItem = {
    CreatedAtAsc: "created_at",
    CreatedAtDesc: "-created_at",
} as const;
export type ListWebhooksRequestSortItem =
    (typeof ListWebhooksRequestSortItem)[keyof typeof ListWebhooksRequestSortItem];
