// This file was auto-generated by Fern from our API Definition.

export const ListAgentsRequestSortItem = {
    CreatedAt: "-created_at",
    AgentName: "-agent_name",
} as const;
export type ListAgentsRequestSortItem = (typeof ListAgentsRequestSortItem)[keyof typeof ListAgentsRequestSortItem];
