// This file was auto-generated by Fern from our API Definition.

export const PatchAgentReasoningEffort = {
    Disabled: "disabled",
    Low: "low",
    Medium: "medium",
    Xhigh: "xhigh",
} as const;
export type PatchAgentReasoningEffort = (typeof PatchAgentReasoningEffort)[keyof typeof PatchAgentReasoningEffort];
