// This file was auto-generated by Fern from our API Definition.

export const ListSessionsRequestSortItem = {
    CreatedAt: "-created_at",
} as const;
export type ListSessionsRequestSortItem =
    (typeof ListSessionsRequestSortItem)[keyof typeof ListSessionsRequestSortItem];
