// This file was auto-generated by Fern from our API Definition.

export const ListSessionsRequestOwner = {
    Me: "me",
    MeInOrganization: "me-in-organization",
    Organization: "organization",
    MeOrOrganization: "me-or-organization",
} as const;
export type ListSessionsRequestOwner = (typeof ListSessionsRequestOwner)[keyof typeof ListSessionsRequestOwner];
