// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../index.js";

export type SendSessionMessagesRequestBody =
    | HaiAgents.SendSessionMessagesRequestBody.UserMessage
    | HaiAgents.SendSessionMessagesRequestBody.Batch;

export namespace SendSessionMessagesRequestBody {
    export interface UserMessage extends HaiAgents.UserMessageEvent {
        type: "user_message";
    }

    export interface Batch extends HaiAgents.UserMessageBatch {
        type: "batch";
    }
}
