// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../index.js";

export type CreateEnvironmentRequest = HaiAgents.CreateEnvironmentRequest.Web;

export namespace CreateEnvironmentRequest {
    export interface Web extends HaiAgents.Browser {
        kind: "web";
    }
}
