// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../index.js";

export type CreateEnvironmentRequest =
    | HaiAgents.CreateEnvironmentRequest.Web
    | HaiAgents.CreateEnvironmentRequest.Desktop
    | HaiAgents.CreateEnvironmentRequest.Android;

export namespace CreateEnvironmentRequest {
    export interface Web extends HaiAgents.Browser {
        kind: "web";
    }

    export interface Desktop extends HaiAgents.Desktop {
        kind: "desktop";
    }

    export interface Android extends HaiAgents.Android {
        kind: "android";
    }
}
