// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../index.js";

export type CreateEnvironmentResponse = HaiAgents.CreateEnvironmentResponse.Web;

export namespace CreateEnvironmentResponse {
    export interface Web extends HaiAgents.Browser {
        kind: "web";
    }
}
