// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../index.js";

export type GetEnvironmentResponse = HaiAgents.GetEnvironmentResponse.Web;

export namespace GetEnvironmentResponse {
    export interface Web extends HaiAgents.Browser {
        kind: "web";
    }
}
