// This file was auto-generated by Fern from our API Definition.

export const ListEnvironmentsRequestSortItem = {
    CreatedAt: "-created_at",
    Id: "id",
} as const;
export type ListEnvironmentsRequestSortItem =
    (typeof ListEnvironmentsRequestSortItem)[keyof typeof ListEnvironmentsRequestSortItem];
