// This file was auto-generated by Fern from our API Definition.

export const ListEnvironmentsRequestSortItem = {
    CreatedAtAsc: "created_at",
    CreatedAtDesc: "-created_at",
    IdAsc: "id",
    IdDesc: "-id",
} as const;
export type ListEnvironmentsRequestSortItem =
    (typeof ListEnvironmentsRequestSortItem)[keyof typeof ListEnvironmentsRequestSortItem];
