// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../index.js";

export type PatchEnvironmentMode = HaiAgents.BrowserVisualMode | HaiAgents.BrowserTextMode;
