// This file was auto-generated by Fern from our API Definition.

export const PatchEnvironmentMode = {
    Visual: "visual",
    Text: "text",
    Multimodal: "multimodal",
} as const;
export type PatchEnvironmentMode = (typeof PatchEnvironmentMode)[keyof typeof PatchEnvironmentMode];
