// This file was auto-generated by Fern from our API Definition.

export const PatchEnvironmentHost = {
    UserDevice: "user_device",
    Cloud: "cloud",
} as const;
export type PatchEnvironmentHost = (typeof PatchEnvironmentHost)[keyof typeof PatchEnvironmentHost];
