// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../index.js";

export type UpdateEnvironmentRequestBody = HaiAgents.UpdateEnvironmentRequestBody.Web;

export namespace UpdateEnvironmentRequestBody {
    export interface Web extends HaiAgents.Browser {
        kind: "web";
    }
}
