// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../index.js";

export type UpdateEnvironmentResponse = HaiAgents.UpdateEnvironmentResponse.Web;

export namespace UpdateEnvironmentResponse {
    export interface Web extends HaiAgents.Browser {
        kind: "web";
    }
}
