// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const ListFilesRequest: core.serialization.Schema<
    serializers.ListFilesRequest.Raw,
    Omit<HaiAgents.ListFilesRequest, "sessionId">
> = core.serialization.object({
    path: core.serialization.string().optional(),
    maxEntries: core.serialization.property("max_entries", core.serialization.number().optional()),
    modifiedBefore: core.serialization.property("modified_before", core.serialization.date().optionalNullable()),
    nameAfter: core.serialization.property("name_after", core.serialization.string().optionalNullable()),
});

export declare namespace ListFilesRequest {
    export interface Raw {
        path?: string | null;
        max_entries?: number | null;
        modified_before?: (string | null | undefined) | null;
        name_after?: (string | null | undefined) | null;
    }
}
