// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const ReadFileRequest: core.serialization.Schema<
    serializers.ReadFileRequest.Raw,
    Omit<HaiAgents.ReadFileRequest, "sessionId">
> = core.serialization.object({
    path: core.serialization.string(),
});

export declare namespace ReadFileRequest {
    export interface Raw {
        path: string;
    }
}
