// This file was auto-generated by Fern from our API Definition.

export const ListSkillsRequestSortItem = {
    CreatedAtAsc: "created_at",
    CreatedAtDesc: "-created_at",
    NameAsc: "name",
    NameDesc: "-name",
} as const;
export type ListSkillsRequestSortItem = (typeof ListSkillsRequestSortItem)[keyof typeof ListSkillsRequestSortItem];
