// This file was auto-generated by Fern from our API Definition.

export const ListSkillsRequestSortItem = {
    CreatedAt: "-created_at",
    Name: "name",
} as const;
export type ListSkillsRequestSortItem = (typeof ListSkillsRequestSortItem)[keyof typeof ListSkillsRequestSortItem];
