// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListEnvironmentsRequest {
    /** Case-insensitive substring match on environment id. */
    id?: string | null;
    /** Filter by environment kind. */
    kind?: HaiAgents.EnvironmentKind | null;
    /** Case-insensitive match on environment id or description. */
    search?: string | null;
    /** Page number (1-based) */
    page?: number;
    /** Number of items per page */
    size?: number;
    /** Sort by field */
    sort?: HaiAgents.ListEnvironmentsRequestSortItem[] | null;
}
