// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface PatchEnvironment {
    id: string;
    headless?: boolean | null;
    width?: number | null;
    height?: number | null;
    startUrl?: string | null;
    sessionId?: string | null;
    mode?: HaiAgents.PatchEnvironmentMode | null;
    pageChars?: number | null;
    vaultId?: string | null;
    pipPackages?: string[] | null;
    env?: Record<string, string | null> | null;
    mcpServers?: HaiAgents.McpServer[] | null;
    servers?: HaiAgents.McpServer[] | null;
    namespace?: string | null;
}
