// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface PatchEnvironment {
    id: string;
    host?: HaiAgents.PatchEnvironmentHost | null;
    startUrl?: string | null;
    headless?: boolean | null;
    sessionId?: string | null;
    mode?: HaiAgents.PatchEnvironmentMode | null;
    vaultId?: string | null;
    browserProfileId?: string | null;
    useDefaultBrowserProfile?: boolean | null;
    persistBrowserProfile?: boolean | null;
    network?: HaiAgents.BrowserNetwork | null;
}
