// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         body: {
 *             id: "id",
 *             headless: true,
 *             width: 1,
 *             height: 1
 *         }
 *     }
 */
export interface UpdateEnvironmentRequest {
    id: string;
    body: HaiAgents.Browser;
}
