// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const CreateWebhook: core.serialization.Schema<serializers.CreateWebhook.Raw, HaiAgents.CreateWebhook> =
    core.serialization.object({
        url: core.serialization.string(),
        enabledEvents: core.serialization.property(
            "enabled_events",
            core.serialization.list(core.serialization.string()).optional(),
        ),
        description: core.serialization.string().optionalNullable(),
    });

export declare namespace CreateWebhook {
    export interface Raw {
        url: string;
        enabled_events?: string[] | null;
        description?: (string | null | undefined) | null;
    }
}
