// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { CronTiming } from "../../../../types/CronTiming.js";
import { SessionRequest } from "../../../../types/SessionRequest.js";

export const CreateSchedule: core.serialization.Schema<serializers.CreateSchedule.Raw, HaiAgents.CreateSchedule> =
    core.serialization.object({
        name: core.serialization.string(),
        description: core.serialization.string().optionalNullable(),
        timing: CronTiming,
        sessionRequest: core.serialization.property("session_request", SessionRequest),
    });

export declare namespace CreateSchedule {
    export interface Raw {
        name: string;
        description?: (string | null | undefined) | null;
        timing: CronTiming.Raw;
        session_request: SessionRequest.Raw;
    }
}
