// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { BrowserNetwork } from "../../../../types/BrowserNetwork.js";
import { McpServer } from "../../../../types/McpServer.js";
import { PatchEnvironmentMode } from "../../types/PatchEnvironmentMode.js";

export const PatchEnvironment: core.serialization.Schema<
    serializers.PatchEnvironment.Raw,
    Omit<HaiAgents.PatchEnvironment, "id">
> = core.serialization.object({
    width: core.serialization.number().optionalNullable(),
    height: core.serialization.number().optionalNullable(),
    startUrl: core.serialization.property("start_url", core.serialization.string().optionalNullable()),
    sessionId: core.serialization.property("session_id", core.serialization.string().optionalNullable()),
    mode: PatchEnvironmentMode.optionalNullable(),
    pageChars: core.serialization.property("page_chars", core.serialization.number().optionalNullable()),
    vaultId: core.serialization.property("vault_id", core.serialization.string().optionalNullable()),
    browserProfileId: core.serialization.property("browser_profile_id", core.serialization.string().optionalNullable()),
    network: BrowserNetwork.optionalNullable(),
    pipPackages: core.serialization.property(
        "pip_packages",
        core.serialization.list(core.serialization.string()).optionalNullable(),
    ),
    env: core.serialization
        .record(core.serialization.string(), core.serialization.string().nullable())
        .optionalNullable(),
    mcpServers: core.serialization.property("mcp_servers", core.serialization.list(McpServer).optionalNullable()),
    servers: core.serialization.list(McpServer).optionalNullable(),
    namespace: core.serialization.string().optionalNullable(),
});

export declare namespace PatchEnvironment {
    export interface Raw {
        width?: (number | null | undefined) | null;
        height?: (number | null | undefined) | null;
        start_url?: (string | null | undefined) | null;
        session_id?: (string | null | undefined) | null;
        mode?: (PatchEnvironmentMode.Raw | null | undefined) | null;
        page_chars?: (number | null | undefined) | null;
        vault_id?: (string | null | undefined) | null;
        browser_profile_id?: (string | null | undefined) | null;
        network?: (BrowserNetwork.Raw | null | undefined) | null;
        pip_packages?: (string[] | null | undefined) | null;
        env?: (Record<string, string | null> | null | undefined) | null;
        mcp_servers?: (McpServer.Raw[] | null | undefined) | null;
        servers?: (McpServer.Raw[] | null | undefined) | null;
        namespace?: (string | null | undefined) | null;
    }
}
