// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { BrowserNetwork } from "../../../../types/BrowserNetwork.js";
import { PatchEnvironmentMode } from "../../types/PatchEnvironmentMode.js";

export const PatchEnvironment: core.serialization.Schema<
    serializers.PatchEnvironment.Raw,
    Omit<HaiAgents.PatchEnvironment, "id">
> = core.serialization.object({
    startUrl: core.serialization.property("start_url", core.serialization.string().optionalNullable()),
    headless: core.serialization.boolean().optionalNullable(),
    mode: PatchEnvironmentMode.optionalNullable(),
    vaultId: core.serialization.property("vault_id", core.serialization.string().optionalNullable()),
    browserProfileId: core.serialization.property("browser_profile_id", core.serialization.string().optionalNullable()),
    network: BrowserNetwork.optionalNullable(),
});

export declare namespace PatchEnvironment {
    export interface Raw {
        start_url?: (string | null | undefined) | null;
        headless?: (boolean | null | undefined) | null;
        mode?: (PatchEnvironmentMode.Raw | null | undefined) | null;
        vault_id?: (string | null | undefined) | null;
        browser_profile_id?: (string | null | undefined) | null;
        network?: (BrowserNetwork.Raw | null | undefined) | null;
    }
}
