// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const ListAgentsRequestSortItem: core.serialization.Schema<
    serializers.ListAgentsRequestSortItem.Raw,
    HaiAgents.ListAgentsRequestSortItem
> = core.serialization.enum_(["created_at", "-created_at", "agent_name", "-agent_name"]);

export declare namespace ListAgentsRequestSortItem {
    export type Raw = "created_at" | "-created_at" | "agent_name" | "-agent_name";
}
