// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Skill } from "../../../types/Skill.js";

export const PatchAgentSkillsItem: core.serialization.Schema<
    serializers.PatchAgentSkillsItem.Raw,
    HaiAgents.PatchAgentSkillsItem
> = core.serialization.undiscriminatedUnion([core.serialization.string(), Skill]);

export declare namespace PatchAgentSkillsItem {
    export type Raw = string | Skill.Raw;
}
