// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const PatchAgentReasoningEffort: core.serialization.Schema<
    serializers.PatchAgentReasoningEffort.Raw,
    HaiAgents.PatchAgentReasoningEffort
> = core.serialization.enum_(["disabled", "low", "medium", "xhigh"]);

export declare namespace PatchAgentReasoningEffort {
    export type Raw = "disabled" | "low" | "medium" | "xhigh";
}
