// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "name",
 *         timing: {
 *             expression: "expression",
 *             timezone: "timezone"
 *         },
 *         sessionRequest: {
 *             agent: "agent"
 *         }
 *     }
 */
export interface CreateSchedule {
    name: string;
    description?: string | null;
    timing: HaiAgents.CronTiming;
    /** Template used to create each scheduled session; re-resolved on every fire. */
    sessionRequest: HaiAgents.SessionRequest;
}
