// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../index.js";

/**
 * @example
 *     {
 *         scheduleId: "schedule_id"
 *     }
 */
export interface ListScheduleRunsRequest {
    scheduleId: string;
    /** Page number (1-based) */
    page?: number;
    /** Number of items per page */
    size?: number;
    /** Sort by field */
    sort?: HaiAgents.ListScheduleRunsRequestSortItem[] | null;
}
