// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../index.js";

/**
 * @example
 *     {
 *         scheduleId: "schedule_id",
 *         body: {}
 *     }
 */
export interface PauseScheduleRequest {
    scheduleId: string;
    body: HaiAgents.PauseSchedule | null;
}
