// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../index.js";

/**
 * @example
 *     {
 *         scheduleId: "schedule_id"
 *     }
 */
export interface UpdateSchedule {
    scheduleId: string;
    name?: string | null;
    description?: string | null;
    timing?: HaiAgents.CronTiming | null;
    sessionRequest?: HaiAgents.SessionRequest | null;
}
