// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ActiveStateChangeData } from "./ActiveStateChangeData.js";

export const ActiveStateChangeEvent: core.serialization.ObjectSchema<
    serializers.ActiveStateChangeEvent.Raw,
    HaiAgents.ActiveStateChangeEvent
> = core.serialization
    .object({
        timestamp: core.serialization.date(),
        data: ActiveStateChangeData,
    })
    .passthrough();

export declare namespace ActiveStateChangeEvent {
    export interface Raw {
        timestamp: string;
        data: ActiveStateChangeData.Raw;
        [key: string]: any;
    }
}
