// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgentErrorData: core.serialization.ObjectSchema<serializers.AgentErrorData.Raw, HaiAgents.AgentErrorData> =
    core.serialization
        .object({
            error: core.serialization.string(),
            trace: core.serialization.string().optional(),
            info: core.serialization
                .record(core.serialization.string(), core.serialization.unknown())
                .optionalNullable(),
        })
        .passthrough();

export declare namespace AgentErrorData {
    export interface Raw {
        error: string;
        trace?: string | null;
        info?: (Record<string, unknown> | null | undefined) | null;
        [key: string]: any;
    }
}
