// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgentRunStatusChangeDataStatus: core.serialization.Schema<
    serializers.AgentRunStatusChangeDataStatus.Raw,
    HaiAgents.AgentRunStatusChangeDataStatus
> = core.serialization.enum_(["running", "paused"]);

export declare namespace AgentRunStatusChangeDataStatus {
    export type Raw = "running" | "paused";
}
