// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Skill } from "./Skill.js";

export const AgentSkillsItem: core.serialization.Schema<serializers.AgentSkillsItem.Raw, HaiAgents.AgentSkillsItem> =
    core.serialization.undiscriminatedUnion([core.serialization.string(), Skill]);

export declare namespace AgentSkillsItem {
    export type Raw = string | Skill.Raw;
}
