// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentRunStatusChangeData } from "./AgentRunStatusChangeData.js";

export const AgentRunStatusChangeEvent: core.serialization.ObjectSchema<
    serializers.AgentRunStatusChangeEvent.Raw,
    HaiAgents.AgentRunStatusChangeEvent
> = core.serialization
    .object({
        timestamp: core.serialization.date(),
        data: AgentRunStatusChangeData,
    })
    .passthrough();

export declare namespace AgentRunStatusChangeEvent {
    export interface Raw {
        timestamp: string;
        data: AgentRunStatusChangeData.Raw;
        [key: string]: any;
    }
}
