// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentRunStatusChangeDataStatus } from "./AgentRunStatusChangeDataStatus.js";

export const AgentRunStatusChangeData: core.serialization.ObjectSchema<
    serializers.AgentRunStatusChangeData.Raw,
    HaiAgents.AgentRunStatusChangeData
> = core.serialization
    .object({
        status: AgentRunStatusChangeDataStatus,
    })
    .passthrough();

export declare namespace AgentRunStatusChangeData {
    export interface Raw {
        status: AgentRunStatusChangeDataStatus.Raw;
        [key: string]: any;
    }
}
