// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { AgentEnvironmentsItem } from "./AgentEnvironmentsItem.js";
import { AgentSkillsItem } from "./AgentSkillsItem.js";

export const Agent: core.serialization.ObjectSchema<serializers.Agent.Raw, HaiAgents.Agent> = core.serialization.object(
    {
        name: core.serialization.string(),
        description: core.serialization.string(),
        environments: core.serialization.list(AgentEnvironmentsItem),
        model: core.serialization.string().optionalNullable(),
        instructions: core.serialization.string().optionalNullable(),
        subagents: core.serialization
            .list(core.serialization.lazy(() => serializers.AgentSubagentsItem))
            .optionalNullable(),
        skills: core.serialization.list(AgentSkillsItem).optionalNullable(),
        answerFormat: core.serialization.property(
            "answer_format",
            core.serialization.record(core.serialization.string(), core.serialization.unknown()).optionalNullable(),
        ),
    },
);

export declare namespace Agent {
    export interface Raw {
        name: string;
        description: string;
        environments: AgentEnvironmentsItem.Raw[];
        model?: (string | null | undefined) | null;
        instructions?: (string | null | undefined) | null;
        subagents?: (serializers.AgentSubagentsItem.Raw[] | null | undefined) | null;
        skills?: (AgentSkillsItem.Raw[] | null | undefined) | null;
        answer_format?: (Record<string, unknown> | null | undefined) | null;
    }
}
