// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentCompletionDataReason } from "./AgentCompletionDataReason.js";

export const AgentCompletionData: core.serialization.ObjectSchema<
    serializers.AgentCompletionData.Raw,
    HaiAgents.AgentCompletionData
> = core.serialization
    .object({
        reason: AgentCompletionDataReason,
    })
    .passthrough();

export declare namespace AgentCompletionData {
    export interface Raw {
        reason: AgentCompletionDataReason.Raw;
        [key: string]: any;
    }
}
