// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AnswerEvent } from "./AnswerEvent.js";
import { ErrorEvent } from "./ErrorEvent.js";
import { FlowEvent } from "./FlowEvent.js";
import { MessageEvent } from "./MessageEvent.js";
import { ObservationEvent } from "./ObservationEvent.js";
import { PolicyEvent } from "./PolicyEvent.js";
import { ToolResultEvent } from "./ToolResultEvent.js";

export const AgentEventData: core.serialization.Schema<serializers.AgentEventData.Raw, HaiAgents.AgentEventData> =
    core.serialization
        .union("kind", {
            answer_event: AnswerEvent,
            error_event: ErrorEvent,
            flow_event: FlowEvent,
            message_event: MessageEvent,
            observation_event: ObservationEvent,
            policy_event: PolicyEvent,
            tool_result: ToolResultEvent,
        })
        .transform<HaiAgents.AgentEventData>({
            transform: (value) => value,
            untransform: (value) => value,
        });

export declare namespace AgentEventData {
    export type Raw =
        | AgentEventData.AnswerEvent
        | AgentEventData.ErrorEvent
        | AgentEventData.FlowEvent
        | AgentEventData.MessageEvent
        | AgentEventData.ObservationEvent
        | AgentEventData.PolicyEvent
        | AgentEventData.ToolResult;

    export interface AnswerEvent extends AnswerEvent.Raw {
        kind: "answer_event";
    }

    export interface ErrorEvent extends ErrorEvent.Raw {
        kind: "error_event";
    }

    export interface FlowEvent extends FlowEvent.Raw {
        kind: "flow_event";
    }

    export interface MessageEvent extends MessageEvent.Raw {
        kind: "message_event";
    }

    export interface ObservationEvent extends ObservationEvent.Raw {
        kind: "observation_event";
    }

    export interface PolicyEvent extends PolicyEvent.Raw {
        kind: "policy_event";
    }

    export interface ToolResult extends ToolResultEvent.Raw {
        kind: "tool_result";
    }
}
