// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentErrorData } from "./AgentErrorData.js";

export const AgentErrorEvent: core.serialization.ObjectSchema<
    serializers.AgentErrorEvent.Raw,
    HaiAgents.AgentErrorEvent
> = core.serialization
    .object({
        timestamp: core.serialization.date(),
        data: AgentErrorData,
    })
    .passthrough();

export declare namespace AgentErrorEvent {
    export interface Raw {
        timestamp: string;
        data: AgentErrorData.Raw;
        [key: string]: any;
    }
}
