// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgentCompletionDataReason: core.serialization.Schema<
    serializers.AgentCompletionDataReason.Raw,
    HaiAgents.AgentCompletionDataReason
> = core.serialization.enum_(["finished", "stopped", "timed_out"]);

export declare namespace AgentCompletionDataReason {
    export type Raw = "finished" | "stopped" | "timed_out";
}
