// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const Android: core.serialization.ObjectSchema<serializers.Android.Raw, HaiAgents.Android> =
    core.serialization.object({
        id: core.serialization.string(),
        sessionId: core.serialization.property("session_id", core.serialization.string().optionalNullable()),
        image: core.serialization.string().optionalNullable(),
        lazy: core.serialization.boolean().optional(),
    });

export declare namespace Android {
    export interface Raw {
        id: string;
        session_id?: (string | null | undefined) | null;
        image?: (string | null | undefined) | null;
        lazy?: boolean | null;
    }
}
