// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AttachmentData } from "./AttachmentData.js";

export const AttachmentEvent: core.serialization.ObjectSchema<
    serializers.AttachmentEvent.Raw,
    HaiAgents.AttachmentEvent
> = core.serialization
    .object({
        timestamp: core.serialization.date(),
        data: AttachmentData,
    })
    .passthrough();

export declare namespace AttachmentEvent {
    export interface Raw {
        timestamp: string;
        data: AttachmentData.Raw;
        [key: string]: any;
    }
}
