// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AttachmentDataOrigin: core.serialization.Schema<
    serializers.AttachmentDataOrigin.Raw,
    HaiAgents.AttachmentDataOrigin
> = core.serialization.enum_(["agent", "user"]);

export declare namespace AttachmentDataOrigin {
    export type Raw = "agent" | "user";
}
