// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AttachmentDataOrigin } from "./AttachmentDataOrigin.js";

export const AttachmentData: core.serialization.ObjectSchema<serializers.AttachmentData.Raw, HaiAgents.AttachmentData> =
    core.serialization
        .object({
            origin: AttachmentDataOrigin,
            name: core.serialization.string(),
            path: core.serialization.string(),
            mediaType: core.serialization.property("media_type", core.serialization.string()),
            sizeBytes: core.serialization.property("size_bytes", core.serialization.number()),
            url: core.serialization.string(),
        })
        .passthrough();

export declare namespace AttachmentData {
    export interface Raw {
        origin: AttachmentDataOrigin.Raw;
        name: string;
        path: string;
        media_type: string;
        size_bytes: number;
        url: string;
        [key: string]: any;
    }
}
