// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const BrowserKind: core.serialization.Schema<serializers.BrowserKind.Raw, HaiAgents.BrowserKind> =
    core.serialization.enum_(["web"]);

export declare namespace BrowserKind {
    export type Raw = "web";
}
