// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { BrowserTextModeType } from "./BrowserTextModeType.js";

export const BrowserTextMode: core.serialization.ObjectSchema<
    serializers.BrowserTextMode.Raw,
    HaiAgents.BrowserTextMode
> = core.serialization.withJsonDefaults(core.serialization.object({
    type: BrowserTextModeType.optional(),
    chunkSize: core.serialization.property("chunk_size", core.serialization.number().optional()),
}), { type: "text" });

export declare namespace BrowserTextMode {
    export interface Raw {
        type?: BrowserTextModeType.Raw | null;
        chunk_size?: number | null;
    }
}
