// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const BrowserTextModeType: core.serialization.Schema<
    serializers.BrowserTextModeType.Raw,
    HaiAgents.BrowserTextModeType
> = core.serialization.enum_(["text"]);

export declare namespace BrowserTextModeType {
    export type Raw = "text";
}
