// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const BrowserNetwork: core.serialization.ObjectSchema<serializers.BrowserNetwork.Raw, HaiAgents.BrowserNetwork> =
    core.serialization.object({
        proxyUrl: core.serialization.property("proxy_url", core.serialization.string().optionalNullable()),
    });

export declare namespace BrowserNetwork {
    export interface Raw {
        proxy_url?: (string | null | undefined) | null;
    }
}
