// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const BrowserVisualModeType: core.serialization.Schema<
    serializers.BrowserVisualModeType.Raw,
    HaiAgents.BrowserVisualModeType
> = core.serialization.enum_(["visual"]);

export declare namespace BrowserVisualModeType {
    export type Raw = "visual";
}
