// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { BrowserKind } from "./BrowserKind.js";
import { BrowserMode } from "./BrowserMode.js";

export const Browser: core.serialization.ObjectSchema<serializers.Browser.Raw, HaiAgents.Browser> =
    core.serialization.object({
        id: core.serialization.string(),
        kind: BrowserKind.optional(),
        headless: core.serialization.boolean(),
        width: core.serialization.number(),
        height: core.serialization.number(),
        startUrl: core.serialization.property("start_url", core.serialization.string().nullable()),
        mode: BrowserMode.optional(),
    });

export declare namespace Browser {
    export interface Raw {
        id: string;
        kind?: BrowserKind.Raw | null;
        headless: boolean;
        width: number;
        height: number;
        start_url?: string | null;
        mode?: BrowserMode.Raw | null;
    }
}
