// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { BrowserVisualModeType } from "./BrowserVisualModeType.js";

export const BrowserVisualMode: core.serialization.ObjectSchema<
    serializers.BrowserVisualMode.Raw,
    HaiAgents.BrowserVisualMode
> = core.serialization.withJsonDefaults(core.serialization.object({
    type: BrowserVisualModeType.optional(),
    width: core.serialization.number().optional(),
    height: core.serialization.number().optional(),
    markdown: core.serialization.boolean().optional(),
}), { type: "visual" });

export declare namespace BrowserVisualMode {
    export interface Raw {
        type?: BrowserVisualModeType.Raw | null;
        width?: number | null;
        height?: number | null;
        markdown?: boolean | null;
    }
}
