// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const BrowserProfileRead: core.serialization.ObjectSchema<
    serializers.BrowserProfileRead.Raw,
    HaiAgents.BrowserProfileRead
> = core.serialization.object({
    id: core.serialization.string(),
    userId: core.serialization.property("user_id", core.serialization.string()),
    orgId: core.serialization.property("org_id", core.serialization.string()),
    name: core.serialization.string(),
    description: core.serialization.string().optionalNullable(),
    browserName: core.serialization.property("browser_name", core.serialization.string()),
    browserVersion: core.serialization.property("browser_version", core.serialization.string()),
    s3Path: core.serialization.property("s3_path", core.serialization.string().optionalNullable()),
    fileSizeBytes: core.serialization.property("file_size_bytes", core.serialization.number().optionalNullable()),
    checksum: core.serialization.string().optionalNullable(),
    usageCount: core.serialization.property("usage_count", core.serialization.number().optional()),
    lastUsedAt: core.serialization.property("last_used_at", core.serialization.date().optionalNullable()),
    labels: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optionalNullable(),
    isDefault: core.serialization.property("is_default", core.serialization.boolean().optional()),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date()),
});

export declare namespace BrowserProfileRead {
    export interface Raw {
        id: string;
        user_id: string;
        org_id: string;
        name: string;
        description?: (string | null | undefined) | null;
        browser_name: string;
        browser_version: string;
        s3_path?: (string | null | undefined) | null;
        file_size_bytes?: (number | null | undefined) | null;
        checksum?: (string | null | undefined) | null;
        usage_count?: number | null;
        last_used_at?: (string | null | undefined) | null;
        labels?: (Record<string, unknown> | null | undefined) | null;
        is_default?: boolean | null;
        created_at: string;
        updated_at: string;
    }
}
