// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const BrowserMode: core.serialization.Schema<serializers.BrowserMode.Raw, HaiAgents.BrowserMode> =
    core.serialization.enum_(["visual", "text", "multimodal"]);

export declare namespace BrowserMode {
    export type Raw = "visual" | "text" | "multimodal";
}
