// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { BrowserProfileRead } from "./BrowserProfileRead.js";

export const BrowserProfileList: core.serialization.ObjectSchema<
    serializers.BrowserProfileList.Raw,
    HaiAgents.BrowserProfileList
> = core.serialization.object({
    total: core.serialization.number(),
    limit: core.serialization.number(),
    offset: core.serialization.number(),
    profiles: core.serialization.list(BrowserProfileRead),
});

export declare namespace BrowserProfileList {
    export interface Raw {
        total: number;
        limit: number;
        offset: number;
        profiles: BrowserProfileRead.Raw[];
    }
}
