// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { BrowserHost } from "./BrowserHost.js";
import { BrowserMode } from "./BrowserMode.js";
import { BrowserNetwork } from "./BrowserNetwork.js";

export const Browser: core.serialization.ObjectSchema<serializers.Browser.Raw, HaiAgents.Browser> =
    core.serialization.object({
        id: core.serialization.string(),
        host: BrowserHost.optional(),
        startUrl: core.serialization.property("start_url", core.serialization.string().optional()),
        headless: core.serialization.boolean().optional(),
        sessionId: core.serialization.property("session_id", core.serialization.string().optionalNullable()),
        mode: BrowserMode.optional(),
        vaultId: core.serialization.property("vault_id", core.serialization.string().optionalNullable()),
        browserProfileId: core.serialization.property(
            "browser_profile_id",
            core.serialization.string().optionalNullable(),
        ),
        useDefaultBrowserProfile: core.serialization.property(
            "use_default_browser_profile",
            core.serialization.boolean().optional(),
        ),
        persistBrowserProfile: core.serialization.property(
            "persist_browser_profile",
            core.serialization.boolean().optional(),
        ),
        network: BrowserNetwork.optionalNullable(),
    });

export declare namespace Browser {
    export interface Raw {
        id: string;
        host?: BrowserHost.Raw | null;
        start_url?: string | null;
        headless?: boolean | null;
        session_id?: (string | null | undefined) | null;
        mode?: BrowserMode.Raw | null;
        vault_id?: (string | null | undefined) | null;
        browser_profile_id?: (string | null | undefined) | null;
        use_default_browser_profile?: boolean | null;
        persist_browser_profile?: boolean | null;
        network?: (BrowserNetwork.Raw | null | undefined) | null;
    }
}
