// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const DesktopHost: core.serialization.Schema<serializers.DesktopHost.Raw, HaiAgents.DesktopHost> =
    core.serialization.enum_(["user_device"]);

export declare namespace DesktopHost {
    export type Raw = "user_device";
}
