// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Browser } from "./Browser.js";

export const Environment: core.serialization.Schema<serializers.Environment.Raw, HaiAgents.Environment> =
    core.serialization
        .union("kind", {
            web: Browser,
        })
        .transform<HaiAgents.Environment>({
            transform: (value) => value,
            untransform: (value) => value,
        });

export declare namespace Environment {
    export type Raw = Environment.Web;

    export interface Web extends Browser.Raw {
        kind: "web";
    }
}
