// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import type * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Browser } from "./Browser.js";

export const Environment: core.serialization.ObjectSchema<serializers.Environment.Raw, HaiAgents.Environment> = Browser;

export declare namespace Environment {
    export type Raw = Browser.Raw;
}
