// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Environment } from "./Environment.js";

export const EnvironmentPage: core.serialization.ObjectSchema<
    serializers.EnvironmentPage.Raw,
    HaiAgents.EnvironmentPage
> = core.serialization.object({
    items: core.serialization.list(Environment),
    total: core.serialization.number(),
    page: core.serialization.number(),
});

export declare namespace EnvironmentPage {
    export interface Raw {
        items: Environment.Raw[];
        total: number;
        page: number;
    }
}
