// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const EnvironmentKind: core.serialization.Schema<serializers.EnvironmentKind.Raw, HaiAgents.EnvironmentKind> =
    core.serialization.enum_(["web"]);

export declare namespace EnvironmentKind {
    export type Raw = "web";
}
