// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ErrorEventKind: core.serialization.Schema<serializers.ErrorEventKind.Raw, HaiAgents.ErrorEventKind> =
    core.serialization.enum_(["error_event"]);

export declare namespace ErrorEventKind {
    export type Raw = "error_event";
}
