// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const FileContentType: core.serialization.Schema<serializers.FileContentType.Raw, HaiAgents.FileContentType> =
    core.serialization.enum_(["base64", "url"]);

export declare namespace FileContentType {
    export type Raw = "base64" | "url";
}
