// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const FileTransferDataDirection: core.serialization.Schema<
    serializers.FileTransferDataDirection.Raw,
    HaiAgents.FileTransferDataDirection
> = core.serialization.enum_(["download", "upload"]);

export declare namespace FileTransferDataDirection {
    export type Raw = "download" | "upload";
}
