// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { FileTransferData } from "./FileTransferData.js";

export const FileTransferEvent: core.serialization.ObjectSchema<
    serializers.FileTransferEvent.Raw,
    HaiAgents.FileTransferEvent
> = core.serialization
    .object({
        timestamp: core.serialization.date(),
        data: FileTransferData,
    })
    .passthrough();

export declare namespace FileTransferEvent {
    export interface Raw {
        timestamp: string;
        data: FileTransferData.Raw;
        [key: string]: any;
    }
}
