// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { FileContentType } from "./FileContentType.js";

export const FileContent: core.serialization.ObjectSchema<serializers.FileContent.Raw, HaiAgents.FileContent> =
    core.serialization.object({
        type: FileContentType.optional(),
        source: core.serialization.string(),
        name: core.serialization.string(),
        mediaType: core.serialization.property("media_type", core.serialization.string().optionalNullable()),
        sizeBytes: core.serialization.property("size_bytes", core.serialization.number().optionalNullable()),
    });

export declare namespace FileContent {
    export interface Raw {
        type?: FileContentType.Raw | null;
        source: string;
        name: string;
        media_type?: (string | null | undefined) | null;
        size_bytes?: (number | null | undefined) | null;
    }
}
