// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const FlowEvent: core.serialization.ObjectSchema<serializers.FlowEvent.Raw, HaiAgents.FlowEvent> =
    core.serialization.object({
        flow: core.serialization.string(),
        origin: core.serialization.string(),
    });

export declare namespace FlowEvent {
    export interface Raw {
        flow: string;
        origin: string;
    }
}
