// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ImageContentType } from "./ImageContentType.js";

export const ImageContent: core.serialization.ObjectSchema<serializers.ImageContent.Raw, HaiAgents.ImageContent> =
    core.serialization.object({
        source: core.serialization.string(),
        type: ImageContentType,
        mediaType: core.serialization.property("media_type", core.serialization.string().optionalNullable()),
    });

export declare namespace ImageContent {
    export interface Raw {
        source: string;
        type: ImageContentType.Raw;
        media_type?: (string | null | undefined) | null;
    }
}
