// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ImageContentType: core.serialization.Schema<serializers.ImageContentType.Raw, HaiAgents.ImageContentType> =
    core.serialization.enum_(["url", "base64"]);

export declare namespace ImageContentType {
    export type Raw = "url" | "base64";
}
