// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const InitiateUploadResponse: core.serialization.ObjectSchema<
    serializers.InitiateUploadResponse.Raw,
    HaiAgents.InitiateUploadResponse
> = core.serialization.object({
    profileId: core.serialization.property("profile_id", core.serialization.string()),
    uploadUrl: core.serialization.property("upload_url", core.serialization.string()),
    uploadFields: core.serialization.property(
        "upload_fields",
        core.serialization.record(core.serialization.string(), core.serialization.string()),
    ),
    uploadExpiresIn: core.serialization.property("upload_expires_in", core.serialization.number()),
});

export declare namespace InitiateUploadResponse {
    export interface Raw {
        profile_id: string;
        upload_url: string;
        upload_fields: Record<string, string>;
        upload_expires_in: number;
    }
}
