// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const JsonValue: core.serialization.Schema<serializers.JsonValue.Raw, HaiAgents.JsonValue> =
    core.serialization.unknown();

export declare namespace JsonValue {
    export type Raw = unknown;
}
