// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const LiveViewUrlData: core.serialization.ObjectSchema<
    serializers.LiveViewUrlData.Raw,
    HaiAgents.LiveViewUrlData
> = core.serialization
    .object({
        liveViewUrl: core.serialization.property("live_view_url", core.serialization.string()),
    })
    .passthrough();

export declare namespace LiveViewUrlData {
    export interface Raw {
        live_view_url: string;
        [key: string]: any;
    }
}
