// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { LiveViewUrlData } from "./LiveViewUrlData.js";

export const LiveViewUrlEvent: core.serialization.ObjectSchema<
    serializers.LiveViewUrlEvent.Raw,
    HaiAgents.LiveViewUrlEvent
> = core.serialization
    .object({
        timestamp: core.serialization.date(),
        data: LiveViewUrlData,
    })
    .passthrough();

export declare namespace LiveViewUrlEvent {
    export interface Raw {
        timestamp: string;
        data: LiveViewUrlData.Raw;
        [key: string]: any;
    }
}
