// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ProxyPool } from "./ProxyPool.js";

export const ManagedProxySelection: core.serialization.ObjectSchema<
    serializers.ManagedProxySelection.Raw,
    HaiAgents.ManagedProxySelection
> = core.serialization.object({
    country: core.serialization.string().optionalNullable(),
    sticky: core.serialization.boolean().optional(),
    pool: ProxyPool.optional(),
});

export declare namespace ManagedProxySelection {
    export interface Raw {
        country?: (string | null | undefined) | null;
        sticky?: boolean | null;
        pool?: ProxyPool.Raw | null;
    }
}
