// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const McpServerTransport: core.serialization.Schema<
    serializers.McpServerTransport.Raw,
    HaiAgents.McpServerTransport
> = core.serialization.enum_(["stdio", "streamable_http", "sse"]);

export declare namespace McpServerTransport {
    export type Raw = "stdio" | "streamable_http" | "sse";
}
