// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { McpServerTransport } from "./McpServerTransport.js";

export const McpServer: core.serialization.ObjectSchema<serializers.McpServer.Raw, HaiAgents.McpServer> =
    core.serialization.object({
        name: core.serialization.string(),
        transport: McpServerTransport,
        command: core.serialization.string().optionalNullable(),
        args: core.serialization.list(core.serialization.string()).optional(),
        env: core.serialization.record(core.serialization.string(), core.serialization.string()).optional(),
        url: core.serialization.string().optionalNullable(),
        headers: core.serialization.record(core.serialization.string(), core.serialization.string()).optional(),
    });

export declare namespace McpServer {
    export interface Raw {
        name: string;
        transport: McpServerTransport.Raw;
        command?: (string | null | undefined) | null;
        args?: string[] | null;
        env?: Record<string, string> | null;
        url?: (string | null | undefined) | null;
        headers?: Record<string, string> | null;
    }
}
