// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ImageContent } from "./ImageContent.js";

export const MessageEventContentItem: core.serialization.Schema<
    serializers.MessageEventContentItem.Raw,
    HaiAgents.MessageEventContentItem
> = core.serialization.undiscriminatedUnion([core.serialization.string(), ImageContent]);

export declare namespace MessageEventContentItem {
    export type Raw = string | ImageContent.Raw;
}
