// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Metrics } from "./Metrics.js";

export const MetricsUpdateData: core.serialization.ObjectSchema<
    serializers.MetricsUpdateData.Raw,
    HaiAgents.MetricsUpdateData
> = core.serialization
    .object({
        metrics: Metrics,
    })
    .passthrough();

export declare namespace MetricsUpdateData {
    export interface Raw {
        metrics: Metrics.Raw;
        [key: string]: any;
    }
}
