// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ModelCost: core.serialization.ObjectSchema<serializers.ModelCost.Raw, HaiAgents.ModelCost> =
    core.serialization.object({
        name: core.serialization.string(),
        inputTokens: core.serialization.property("input_tokens", core.serialization.number()),
        outputTokens: core.serialization.property("output_tokens", core.serialization.number()),
        reasoningTokens: core.serialization.property("reasoning_tokens", core.serialization.number()),
        inputCost: core.serialization.property("input_cost", core.serialization.number().optionalNullable()),
        outputCost: core.serialization.property("output_cost", core.serialization.number().optionalNullable()),
        reasoningCost: core.serialization.property("reasoning_cost", core.serialization.number().optionalNullable()),
        totalCost: core.serialization.property("total_cost", core.serialization.number().optionalNullable()),
    });

export declare namespace ModelCost {
    export interface Raw {
        name: string;
        input_tokens: number;
        output_tokens: number;
        reasoning_tokens: number;
        input_cost?: (number | null | undefined) | null;
        output_cost?: (number | null | undefined) | null;
        reasoning_cost?: (number | null | undefined) | null;
        total_cost?: (number | null | undefined) | null;
    }
}
