// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ImageContent } from "./ImageContent.js";

export const ObservationEvent: core.serialization.ObjectSchema<
    serializers.ObservationEvent.Raw,
    HaiAgents.ObservationEvent
> = core.serialization.object({
    type: core.serialization.string().optionalNullable(),
    text: core.serialization.string().optionalNullable(),
    image: ImageContent.optionalNullable(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace ObservationEvent {
    export interface Raw {
        type?: (string | null | undefined) | null;
        text?: (string | null | undefined) | null;
        image?: (ImageContent.Raw | null | undefined) | null;
        metadata?: Record<string, unknown> | null;
    }
}
