// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const OnePasswordConfigProvider: core.serialization.Schema<
    serializers.OnePasswordConfigProvider.Raw,
    HaiAgents.OnePasswordConfigProvider
> = core.serialization.enum_(["onepassword"]);

export declare namespace OnePasswordConfigProvider {
    export type Raw = "onepassword";
}
