// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ScheduleRunRecord } from "./ScheduleRunRecord.js";

export const PageScheduleRunRecord: core.serialization.ObjectSchema<
    serializers.PageScheduleRunRecord.Raw,
    HaiAgents.PageScheduleRunRecord
> = core.serialization.object({
    items: core.serialization.list(ScheduleRunRecord),
    total: core.serialization.number(),
    page: core.serialization.number(),
});

export declare namespace PageScheduleRunRecord {
    export interface Raw {
        items: ScheduleRunRecord.Raw[];
        total: number;
        page: number;
    }
}
