// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";

export const PageAgent: core.serialization.ObjectSchema<serializers.PageAgent.Raw, HaiAgents.PageAgent> =
    core.serialization.object({
        items: core.serialization.list(core.serialization.lazyObject(() => serializers.Agent)),
        total: core.serialization.number(),
        page: core.serialization.number(),
    });

export declare namespace PageAgent {
    export interface Raw {
        items: serializers.Agent.Raw[];
        total: number;
        page: number;
    }
}
