// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { SessionSummary } from "./SessionSummary.js";

export const PageSessionSummary: core.serialization.ObjectSchema<
    serializers.PageSessionSummary.Raw,
    HaiAgents.PageSessionSummary
> = core.serialization.object({
    items: core.serialization.list(SessionSummary),
    total: core.serialization.number(),
    page: core.serialization.number(),
});

export declare namespace PageSessionSummary {
    export interface Raw {
        items: SessionSummary.Raw[];
        total: number;
        page: number;
    }
}
