// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ScheduleRecord } from "./ScheduleRecord.js";

export const PageScheduleRecord: core.serialization.ObjectSchema<
    serializers.PageScheduleRecord.Raw,
    HaiAgents.PageScheduleRecord
> = core.serialization.object({
    items: core.serialization.list(ScheduleRecord),
    total: core.serialization.number(),
    page: core.serialization.number(),
});

export declare namespace PageScheduleRecord {
    export interface Raw {
        items: ScheduleRecord.Raw[];
        total: number;
        page: number;
    }
}
