// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Skill } from "./Skill.js";

export const PageSkill: core.serialization.ObjectSchema<serializers.PageSkill.Raw, HaiAgents.PageSkill> =
    core.serialization.object({
        items: core.serialization.list(Skill),
        total: core.serialization.number(),
        page: core.serialization.number(),
    });

export declare namespace PageSkill {
    export interface Raw {
        items: Skill.Raw[];
        total: number;
        page: number;
    }
}
