// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { SessionEvent } from "./SessionEvent.js";

export const PageSessionEvent: core.serialization.ObjectSchema<
    serializers.PageSessionEvent.Raw,
    HaiAgents.PageSessionEvent
> = core.serialization.object({
    items: core.serialization.list(SessionEvent),
    total: core.serialization.number(),
    page: core.serialization.number(),
});

export declare namespace PageSessionEvent {
    export interface Raw {
        items: SessionEvent.Raw[];
        total: number;
        page: number;
    }
}
