// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const PauseSchedule: core.serialization.ObjectSchema<serializers.PauseSchedule.Raw, HaiAgents.PauseSchedule> =
    core.serialization.object({
        note: core.serialization.string().optionalNullable(),
    });

export declare namespace PauseSchedule {
    export interface Raw {
        note?: (string | null | undefined) | null;
    }
}
