// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ToolRequest } from "./ToolRequest.js";

export const PolicyEvent: core.serialization.ObjectSchema<serializers.PolicyEvent.Raw, HaiAgents.PolicyEvent> =
    core.serialization.object({
        reasoningContent: core.serialization.property(
            "reasoning_content",
            core.serialization.string().optionalNullable(),
        ),
        content: core.serialization.string().optionalNullable(),
        toolReqs: core.serialization.property("tool_reqs", core.serialization.list(ToolRequest).optional()),
        validationErrors: core.serialization.property(
            "validation_errors",
            core.serialization.list(core.serialization.string()).optional(),
        ),
    });

export declare namespace PolicyEvent {
    export interface Raw {
        reasoning_content?: (string | null | undefined) | null;
        content?: (string | null | undefined) | null;
        tool_reqs?: ToolRequest.Raw[] | null;
        validation_errors?: string[] | null;
    }
}
