// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const QuotaStatusScope: core.serialization.Schema<serializers.QuotaStatusScope.Raw, HaiAgents.QuotaStatusScope> =
    core.serialization.enum_(["user", "org"]);

export declare namespace QuotaStatusScope {
    export type Raw = "user" | "org";
}
