// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ReadFileResponse: core.serialization.ObjectSchema<
    serializers.ReadFileResponse.Raw,
    HaiAgents.ReadFileResponse
> = core.serialization.object({
    path: core.serialization.string(),
    contentBase64: core.serialization.property("content_base64", core.serialization.string()),
    sizeBytes: core.serialization.property("size_bytes", core.serialization.number()),
    modifiedAt: core.serialization.property("modified_at", core.serialization.date()),
});

export declare namespace ReadFileResponse {
    export interface Raw {
        path: string;
        content_base64: string;
        size_bytes: number;
        modified_at: string;
    }
}
