// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { RequestStartDispatchedData } from "./RequestStartDispatchedData.js";

export const RequestStartDispatchedEvent: core.serialization.ObjectSchema<
    serializers.RequestStartDispatchedEvent.Raw,
    HaiAgents.RequestStartDispatchedEvent
> = core.serialization
    .object({
        timestamp: core.serialization.date(),
        data: RequestStartDispatchedData,
    })
    .passthrough();

export declare namespace RequestStartDispatchedEvent {
    export interface Raw {
        timestamp: string;
        data: RequestStartDispatchedData.Raw;
        [key: string]: any;
    }
}
