// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { RunnerSessionData } from "./RunnerSessionData.js";

export const RunnerSessionEvent: core.serialization.ObjectSchema<
    serializers.RunnerSessionEvent.Raw,
    HaiAgents.RunnerSessionEvent
> = core.serialization
    .object({
        timestamp: core.serialization.date(),
        data: RunnerSessionData,
    })
    .passthrough();

export declare namespace RunnerSessionEvent {
    export interface Raw {
        timestamp: string;
        data: RunnerSessionData.Raw;
        [key: string]: any;
    }
}
