// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ScheduleRunRecordStatus: core.serialization.Schema<
    serializers.ScheduleRunRecordStatus.Raw,
    HaiAgents.ScheduleRunRecordStatus
> = core.serialization.enum_(["created", "skipped_overlap", "skipped_quota", "error"]);

export declare namespace ScheduleRunRecordStatus {
    export type Raw = "created" | "skipped_overlap" | "skipped_quota" | "error";
}
