// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CronTiming } from "./CronTiming.js";
import { SessionRequest } from "./SessionRequest.js";

export const ScheduleRecord: core.serialization.ObjectSchema<serializers.ScheduleRecord.Raw, HaiAgents.ScheduleRecord> =
    core.serialization.object({
        id: core.serialization.string(),
        name: core.serialization.string(),
        description: core.serialization.string().nullable(),
        timing: CronTiming,
        sessionRequest: core.serialization.property("session_request", SessionRequest),
        paused: core.serialization.boolean(),
        pauseNote: core.serialization.property("pause_note", core.serialization.string().nullable()),
        nextRunTimes: core.serialization.property("next_run_times", core.serialization.list(core.serialization.date())),
        lastRunAt: core.serialization.property("last_run_at", core.serialization.date().nullable()),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        updatedAt: core.serialization.property("updated_at", core.serialization.date()),
    });

export declare namespace ScheduleRecord {
    export interface Raw {
        id: string;
        name: string;
        description?: string | null;
        timing: CronTiming.Raw;
        session_request: SessionRequest.Raw;
        paused: boolean;
        pause_note?: string | null;
        next_run_times: string[];
        last_run_at?: string | null;
        created_at: string;
        updated_at: string;
    }
}
