// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SessionChangesAnswer: core.serialization.Schema<
    serializers.SessionChangesAnswer.Raw,
    HaiAgents.SessionChangesAnswer
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.record(core.serialization.string(), core.serialization.unknown()),
]);

export declare namespace SessionChangesAnswer {
    export type Raw = string | Record<string, unknown>;
}
