// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";

export const SessionRequestAgent: core.serialization.Schema<
    serializers.SessionRequestAgent.Raw,
    HaiAgents.SessionRequestAgent
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.lazyObject(() => serializers.Agent),
]);

export declare namespace SessionRequestAgent {
    export type Raw = string | serializers.Agent.Raw;
}
