// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { SessionEventZero } from "./SessionEventZero.js";
import { TrajectoryEvent } from "./TrajectoryEvent.js";

export const SessionEvent: core.serialization.Schema<serializers.SessionEvent.Raw, HaiAgents.SessionEvent> =
    core.serialization.undiscriminatedUnion([SessionEventZero, TrajectoryEvent]);

export declare namespace SessionEvent {
    export type Raw = SessionEventZero.Raw | TrajectoryEvent.Raw;
}
