// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { SessionRequestAgent } from "./SessionRequestAgent.js";
import { SessionRequestMessages } from "./SessionRequestMessages.js";

export const SessionRequest: core.serialization.ObjectSchema<serializers.SessionRequest.Raw, HaiAgents.SessionRequest> =
    core.serialization.object({
        agent: SessionRequestAgent,
        messages: SessionRequestMessages.optionalNullable(),
        maxSteps: core.serialization.property("max_steps", core.serialization.number().optionalNullable()),
        maxTimeS: core.serialization.property("max_time_s", core.serialization.number().optionalNullable()),
        idleTimeoutS: core.serialization.property("idle_timeout_s", core.serialization.number().optionalNullable()),
        queue: core.serialization.boolean().optional(),
        groupId: core.serialization.property("group_id", core.serialization.string().optionalNullable()),
        parentSessionId: core.serialization.property(
            "parent_session_id",
            core.serialization.string().optionalNullable(),
        ),
        overrides: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    });

export declare namespace SessionRequest {
    export interface Raw {
        agent: SessionRequestAgent.Raw;
        messages?: (SessionRequestMessages.Raw | null | undefined) | null;
        max_steps?: (number | null | undefined) | null;
        max_time_s?: (number | null | undefined) | null;
        idle_timeout_s?: (number | null | undefined) | null;
        queue?: boolean | null;
        group_id?: (string | null | undefined) | null;
        parent_session_id?: (string | null | undefined) | null;
        overrides?: Record<string, unknown> | null;
    }
}
