// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { SessionRequest } from "./SessionRequest.js";
import { SessionStatus } from "./SessionStatus.js";

export const Session: core.serialization.ObjectSchema<serializers.Session.Raw, HaiAgents.Session> =
    core.serialization.object({
        id: core.serialization.string(),
        request: SessionRequest,
        status: SessionStatus,
        agentViewUrl: core.serialization.property("agent_view_url", core.serialization.string().optionalNullable()),
        latestAnswer: core.serialization.property("latest_answer", core.serialization.unknown().optional()),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        startedAt: core.serialization.property("started_at", core.serialization.date().optionalNullable()),
        finishedAt: core.serialization.property("finished_at", core.serialization.date().optionalNullable()),
    });

export declare namespace Session {
    export interface Raw {
        id: string;
        request: SessionRequest.Raw;
        status: SessionStatus.Raw;
        agent_view_url?: (string | null | undefined) | null;
        latest_answer?: unknown | null;
        created_at: string;
        started_at?: (string | null | undefined) | null;
        finished_at?: (string | null | undefined) | null;
    }
}
