// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ModelUsage } from "./ModelUsage.js";
import { TrajectoryStatus } from "./TrajectoryStatus.js";

export const SessionStatus: core.serialization.ObjectSchema<serializers.SessionStatus.Raw, HaiAgents.SessionStatus> =
    core.serialization.object({
        status: TrajectoryStatus,
        error: core.serialization.string().optionalNullable(),
        steps: core.serialization.number().optional(),
        usagePerModel: core.serialization.property("usage_per_model", core.serialization.list(ModelUsage).optional()),
        subagentSessionIds: core.serialization.property(
            "subagent_session_ids",
            core.serialization.list(core.serialization.string()).optional(),
        ),
    });

export declare namespace SessionStatus {
    export interface Raw {
        status: TrajectoryStatus.Raw;
        error?: (string | null | undefined) | null;
        steps?: number | null;
        usage_per_model?: ModelUsage.Raw[] | null;
        subagent_session_ids?: string[] | null;
    }
}
