// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SessionErrorCode: core.serialization.Schema<serializers.SessionErrorCode.Raw, HaiAgents.SessionErrorCode> =
    core.serialization.enum_(["environment_error", "no_answer", "answer_validation", "timeout", "internal"]);

export declare namespace SessionErrorCode {
    export type Raw = "environment_error" | "no_answer" | "answer_validation" | "timeout" | "internal";
}
