// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ShareLink: core.serialization.ObjectSchema<serializers.ShareLink.Raw, HaiAgents.ShareLink> =
    core.serialization.object({
        shareUrl: core.serialization.property("share_url", core.serialization.string()),
    });

export declare namespace ShareLink {
    export interface Raw {
        share_url: string;
    }
}
