// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const Skill: core.serialization.ObjectSchema<serializers.Skill.Raw, HaiAgents.Skill> = core.serialization.object(
    {
        name: core.serialization.string(),
        description: core.serialization.string(),
        body: core.serialization.string(),
        source: core.serialization.string().optionalNullable(),
        urlPattern: core.serialization.property("url_pattern", core.serialization.string().optionalNullable()),
    },
);

export declare namespace Skill {
    export interface Raw {
        name: string;
        description: string;
        body: string;
        source?: (string | null | undefined) | null;
        url_pattern?: (string | null | undefined) | null;
    }
}
