// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TokenQuotaStatus: core.serialization.ObjectSchema<
    serializers.TokenQuotaStatus.Raw,
    HaiAgents.TokenQuotaStatus
> = core.serialization.object({
    limit: core.serialization.number().nullable(),
    used: core.serialization.number().nullable(),
    remaining: core.serialization.number().nullable(),
    windowStart: core.serialization.property("window_start", core.serialization.date()),
    windowEnd: core.serialization.property("window_end", core.serialization.date().nullable()),
});

export declare namespace TokenQuotaStatus {
    export interface Raw {
        limit?: number | null;
        used?: number | null;
        remaining?: number | null;
        window_start: string;
        window_end?: string | null;
    }
}
