// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ToolResultBatchResultsItem } from "./ToolResultBatchResultsItem.js";
import { ToolResultBatchType } from "./ToolResultBatchType.js";

export const ToolResultBatch: core.serialization.ObjectSchema<
    serializers.ToolResultBatch.Raw,
    HaiAgents.ToolResultBatch
> = core.serialization.withJsonDefaults(core.serialization.object({
    type: ToolResultBatchType.optional(),
    results: core.serialization.list(ToolResultBatchResultsItem),
}), { type: "batch" });

export declare namespace ToolResultBatch {
    export interface Raw {
        type?: ToolResultBatchType.Raw | null;
        results: ToolResultBatchResultsItem.Raw[];
    }
}
