// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ToolResultEventType: core.serialization.Schema<
    serializers.ToolResultEventType.Raw,
    HaiAgents.ToolResultEventType
> = core.serialization.enum_(["tool_result"]);

export declare namespace ToolResultEventType {
    export type Raw = "tool_result";
}
