// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { JsonValue } from "./JsonValue.js";
import { ToolRequest } from "./ToolRequest.js";
import { ToolResultEventKind } from "./ToolResultEventKind.js";

export const ToolResultEvent: core.serialization.ObjectSchema<
    serializers.ToolResultEvent.Raw,
    HaiAgents.ToolResultEvent
> = core.serialization.withJsonDefaults(core.serialization.object({
    kind: ToolResultEventKind.optional(),
    toolReq: core.serialization.property("tool_req", ToolRequest),
    result: JsonValue.optional(),
}), { kind: "tool_result" });

export declare namespace ToolResultEvent {
    export interface Raw {
        kind?: ToolResultEventKind.Raw | null;
        tool_req: ToolRequest.Raw;
        result?: (JsonValue.Raw | undefined) | null;
    }
}
