// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ToolDefinition: core.serialization.ObjectSchema<serializers.ToolDefinition.Raw, HaiAgents.ToolDefinition> =
    core.serialization.object({
        name: core.serialization.string(),
        description: core.serialization.string(),
        inputSchema: core.serialization.property(
            "input_schema",
            core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
        ),
    });

export declare namespace ToolDefinition {
    export interface Raw {
        name: string;
        description: string;
        input_schema?: Record<string, unknown> | null;
    }
}
