// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ToolRequest: core.serialization.ObjectSchema<serializers.ToolRequest.Raw, HaiAgents.ToolRequest> =
    core.serialization.object({
        toolName: core.serialization.property("tool_name", core.serialization.string()),
        args: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
        id: core.serialization.string().optionalNullable(),
    });

export declare namespace ToolRequest {
    export interface Raw {
        tool_name: string;
        args?: Record<string, unknown> | null;
        id?: (string | null | undefined) | null;
    }
}
