// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ToolResultEvent } from "./ToolResultEvent.js";

export const ToolResultBatch: core.serialization.ObjectSchema<
    serializers.ToolResultBatch.Raw,
    HaiAgents.ToolResultBatch
> = core.serialization.object({
    results: core.serialization.list(ToolResultEvent),
});

export declare namespace ToolResultBatch {
    export interface Raw {
        results: ToolResultEvent.Raw[];
    }
}
