// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { UserMessageEventType } from "./UserMessageEventType.js";

export const UserMessageEvent: core.serialization.ObjectSchema<
    serializers.UserMessageEvent.Raw,
    HaiAgents.UserMessageEvent
> = core.serialization.object({
    type: UserMessageEventType.optional(),
    message: core.serialization.string(),
    images: core.serialization.list(core.serialization.string()).optional(),
    callerId: core.serialization.property("caller_id", core.serialization.string().optional()),
});

export declare namespace UserMessageEvent {
    export interface Raw {
        type?: UserMessageEventType.Raw | null;
        message: string;
        images?: string[] | null;
        caller_id?: string | null;
    }
}
