// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ValidationErrorLocItem: core.serialization.Schema<
    serializers.ValidationErrorLocItem.Raw,
    HaiAgents.ValidationErrorLocItem
> = core.serialization.undiscriminatedUnion([core.serialization.string(), core.serialization.number()]);

export declare namespace ValidationErrorLocItem {
    export type Raw = string | number;
}
