// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const VaultHealth: core.serialization.ObjectSchema<serializers.VaultHealth.Raw, HaiAgents.VaultHealth> =
    core.serialization.object({
        ok: core.serialization.boolean(),
        error: core.serialization.string().optionalNullable(),
    });

export declare namespace VaultHealth {
    export interface Raw {
        ok: boolean;
        error?: (string | null | undefined) | null;
    }
}
