// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { VaultConfigRead } from "./VaultConfigRead.js";

export const VaultConfigList: core.serialization.ObjectSchema<
    serializers.VaultConfigList.Raw,
    HaiAgents.VaultConfigList
> = core.serialization.object({
    total: core.serialization.number(),
    limit: core.serialization.number(),
    offset: core.serialization.number(),
    vaults: core.serialization.list(VaultConfigRead),
});

export declare namespace VaultConfigList {
    export interface Raw {
        total: number;
        limit: number;
        offset: number;
        vaults: VaultConfigRead.Raw[];
    }
}
