// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { OnePasswordConfig } from "./OnePasswordConfig.js";

export const VaultConfigRead: core.serialization.ObjectSchema<
    serializers.VaultConfigRead.Raw,
    HaiAgents.VaultConfigRead
> = core.serialization.object({
    id: core.serialization.string(),
    orgId: core.serialization.property("org_id", core.serialization.string()),
    name: core.serialization.string(),
    providerConfig: core.serialization.property("provider_config", OnePasswordConfig),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date()),
});

export declare namespace VaultConfigRead {
    export interface Raw {
        id: string;
        org_id: string;
        name: string;
        provider_config: OnePasswordConfig.Raw;
        created_at: string;
        updated_at: string;
    }
}
