// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const WebhookPingResult: core.serialization.ObjectSchema<
    serializers.WebhookPingResult.Raw,
    HaiAgents.WebhookPingResult
> = core.serialization.object({
    responseStatus: core.serialization.property("response_status", core.serialization.number()),
});

export declare namespace WebhookPingResult {
    export interface Raw {
        response_status: number;
    }
}
