// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const WebhookRecordLastDeliveryStatus: core.serialization.Schema<
    serializers.WebhookRecordLastDeliveryStatus.Raw,
    HaiAgents.WebhookRecordLastDeliveryStatus
> = core.serialization.enum_(["succeeded", "failed"]);

export declare namespace WebhookRecordLastDeliveryStatus {
    export type Raw = "succeeded" | "failed";
}
