// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const WebhookWithSecret: core.serialization.ObjectSchema<
    serializers.WebhookWithSecret.Raw,
    HaiAgents.WebhookWithSecret
> = core.serialization.object({
    id: core.serialization.string(),
    url: core.serialization.string(),
    enabledEvents: core.serialization.property("enabled_events", core.serialization.list(core.serialization.string())),
    description: core.serialization.string().nullable(),
    disabled: core.serialization.boolean(),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date()),
    secret: core.serialization.string(),
});

export declare namespace WebhookWithSecret {
    export interface Raw {
        id: string;
        url: string;
        enabled_events: string[];
        description?: string | null;
        disabled: boolean;
        created_at: string;
        updated_at: string;
        secret: string;
    }
}
