// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { WorkstationHost } from "./WorkstationHost.js";

export const Workstation: core.serialization.ObjectSchema<serializers.Workstation.Raw, HaiAgents.Workstation> =
    core.serialization.withJsonDefaults(core.serialization.object({
        id: core.serialization.string(),
        host: WorkstationHost.optional(),
    }), { host: "cloud" });

export declare namespace Workstation {
    export interface Raw {
        id: string;
        host?: WorkstationHost.Raw | null;
    }
}
