// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const PatchSkill: core.serialization.Schema<
    serializers.PatchSkill.Raw,
    Omit<HaiAgents.PatchSkill, "name">
> = core.serialization.object({
    description: core.serialization.string().optionalNullable(),
    body: core.serialization.string().optionalNullable(),
    source: core.serialization.string().optionalNullable(),
    urlPattern: core.serialization.property("url_pattern", core.serialization.string().optionalNullable()),
});

export declare namespace PatchSkill {
    export interface Raw {
        description?: (string | null | undefined) | null;
        body?: (string | null | undefined) | null;
        source?: (string | null | undefined) | null;
        url_pattern?: (string | null | undefined) | null;
    }
}
