// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         vaultId: "vault_id",
 *         token: "token"
 *     }
 */
export interface VaultTokenRotateRequest {
    vaultId: string;
    token: string;
}
