// This file was auto-generated by Fern from our API Definition.

import type * as HaiAgents from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "name",
 *         providerConfig: {
 *             opVaultId: "op_vault_id"
 *         },
 *         token: "token"
 *     }
 */
export interface VaultCreateRequest {
    name: string;
    providerConfig: HaiAgents.OnePasswordConfig;
    token: string;
}
