// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         url: "url"
 *     }
 */
export interface CreateWebhook {
    url: string;
    /** Event types delivered to this webhook. '*' subscribes to all current and future types. */
    enabledEvents?: string[];
    description?: string | null;
}
