// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         webhookId: "webhook_id"
 *     }
 */
export interface UpdateWebhook {
    webhookId: string;
    url?: string | null;
    enabledEvents?: string[] | null;
    description?: string | null;
    disabled?: boolean | null;
}
